- build.gradle
Hi,
I'm starting to play around with the code at McKay-Brothers.
Just had to fix the hardcoded thrift path in gradle build file.
Can this be changed, thrift shall be in the PATH anyway, no ?
> Fix hardcoded thrift path

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Hi,
Is GTSHelper.quicksortByLocation still used it doesn't seem to be called ?
> Fix GTSHelper.quicksortByLocation

- BUILDING.md
Add some lines to build Warp10 with thrift-0.9.1 on  MacOS
> Change on building.md to build Warp10 on Mac OS

- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
- warp10/src/main/java/io/warp10/continuum/sensision/SensisionConstants.java
- warp10/src/main/java/io/warp10/continuum/store/Store.java
- warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java
- warp10/src/main/thrift/io_warp10_continuum_store_thrift_data.thrift
For accounting purposes, I need to have a fine grained visibility on the number of points deleted by a particular user. This change reports in Sensision the count of deleted points associated to the owner (and app if present).
This is optional (and disabled by default) for the HBase version, and always active for the standalone version.
> Added detailed deletion metrics

- build.gradle
HbaseFilters is not a maven dependence, but an install component for HBase used by Warp10 platform.
> Change repo from maven to generic

- build.gradle
- warp10/src/main/sh/package.sh
warp10 - Changelog
==================
Unreleased
----------
* Changelist to make Warp10 compatible with JDK7 again...
* Fix extension .tar.gz
* Refactored to index classes per owner instead of per producer as producer is only rarely specified in ReadTokens.
* Added forcing of GC right after loading the initial GTS. Changed type of labelValues to use an array instead of a List
* Addec class statistics in LOG message
* Added INFO log message with detailed stats on directory search.
* Added support for specifying partition.assignment.strategy. Corrected minor tweaks for client.id configuration
* Added calls to maxLimits
* Modified a catch clause so we trap IllegalArgumentException which is thrown instead of IOException when closing a table.
* Added publishing or per server metrics for HBase …
> Add Changelog

- warp10/src/main/java/io/warp10/continuum/KafkaWebCallService.java
- warp10/src/main/java/io/warp10/continuum/geo/GeoDirectory.java
- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
- warp10/src/main/java/io/warp10/continuum/plasma/PlasmaBackEnd.java
- warp10/src/main/java/io/warp10/script/ScriptRunner.java
As mentioned in the documentation, http://kafka.apache.org/documentation.html#producerconfigs, zookeeper.connect doest not exist for KafkaProducer. Removing it also correct unwanted Warning log "WARN  utils.VerifiableProperties - Property zookeeper.connect is not valid" that can lead to unnecessary debugging.
> Remove zookeeper.connect propertie for producerconfig

- build.gradle
- etc/conf-standalone.template
- warp10/src/main/java/io/warp10/SortedPathIterator.java
- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/continuum/ingress/DatalogForwarder.java
- warp10/src/main/java/io/warp10/continuum/sensision/SensisionConstants.java
- warp10/src/main/java/io/warp10/continuum/store/Constants.java
- warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java
- warp10/src/main/java/io/warp10/standalone/StandaloneIngressHandler.java
- warp10/src/main/java/io/warp10/standalone/StandaloneStreamUpdateHandler.java
- warp10/src/main/java/io/warp10/standalone/Warp.java
- warp10/src/main/thrift/io_warp10_continuum_store_thrift_data.thrift
Adds a datalog feature to forward UPDATE/META/DELETE actions from one platform to another. Very useful to build an in-memory cache in front of a distributed platform for example.
> Standalone datalog forwarder

- warp10/src/main/java/io/warp10/script/functions/ADDDAYS.java
- warp10/src/main/java/io/warp10/script/functions/ADDMONTHS.java
- warp10/src/main/java/io/warp10/script/functions/ADDYEARS.java
Based on documentation timezone parameter should be optional for timestamp input but else-if condition in code makes it mandatory. With this pull request those conditions expect also Long on top of stack as timestamp.
> Made Timezone optional for ADDDAYS, ADDMONTHS, ADDYEARS while modifying timestamp

- etc/conf-standalone.template
Fixed typo for parameters:
#datalog.forwarder.deleteforwarded = true
#datalog.forwarder.deleteignored = true
> Fixed standalone config template

- warp10/src/main/java/io/warp10/continuum/gts/GTSEncoder.java
Removed redundant buffers.
Added method to create an 'unsafe' decoder backed by the encoder's array. Such a decoder should only be used while the encoder is not modified.
> Optimized buffer allocation

- warp10/src/main/java/io/warp10/worf/WorfCLI.java
Allow to pass labels as arguments to create WRITE tokens that carry fixed labels inside the token.
> Added labels to Worf CLI arguments

- etc/conf-distributed.template
- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/continuum/store/Store.java
Add support for consumerid infix in Kafka ConsumerConnector to identify consumer instances running on the same host
> Add support for consumerid in Kafka ConsumerConnector

- warp10/src/main/java/io/warp10/script/functions/STL.java
STLESDTEST and HYBRIDTEST weren't able to handle the case where ROBUST parameter of their STL parameters was not set.
> bugfix in STLESDTEST and HYBRIDTEST

- warp10/src/main/java/io/warp10/continuum/ThrottlingManager.java
- warp10/src/main/java/io/warp10/continuum/sensision/SensisionConstants.java
This PR is adding a new metric called *warp.estimators.resets*. Thanks to it, Warp10 administrators can keep track of estimators resets per producer and per app. 
This is also fixing a bad metric name when resetting a per-app estimator.
> Add new metric when an estimator is reset 

- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
Missing or incorrect code for modifying the MAXGEOCELLS value.
Note that this value mostly unused as GEOWKT (non-uniform version) and GEOJSON ignore this setting.
> Fixed some configuration setting and usage for MAXGEOCELLS.

- warp10/src/main/java/io/warp10/script/functions/MAXRECURSION.java
MAXRECURSION could not be used because of incorrect/missing casts, fixed that by forcing casts to int.
Same issue as https://github.com/cityzendata/warp10-platform/issues/21
> Fixed MAXRECURSION long/int casts.

- warp10/src/main/java/io/warp10/script/functions/SPLIT.java
SPLIT didn't do any type check. So it runs seamlessly on a SET, on a LIST, a MAP.
e.g. results on lists include the [ or ] characters in the results, leading to really strang results.
> Added type check on SPLIT.

- warp10/src/main/java/io/warp10/script/processing/color/PcolorMode.java
- warp10/src/main/java/io/warp10/script/processing/rendering/PGraphics.java
By default, ARGB was defined. But in processing, ARGB is not managed by
colorCalc function.
switch (colorMode) {
case RGB:
... (also manage alpha)
case HSB:
...
colorCalc is called by every functions which takes a color as input. So,
all signatures were broken for these functions : only grayscale and
direct ARGB long produce the expected result.
> Fix the RGB color management in processing functions

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
These two functions have no implementation, but are exposed by
FUNCTIONS extension. Safer to remove them from code.
> Removed not implemented functions

- warp10/src/main/java/io/warp10/script/processing/shape/PbeginShape.java
- warp10/src/main/java/io/warp10/script/processing/shape/PendShape.java
Allow to call PendShape and PbeginShape without arguments.
Now compliant to Processing doc.
> Add new signature to processing endShape beginShape

- warp10/src/main/java/io/warp10/script/aggregator/MAD.java
Unitary list returned null->fixed.
Nulls where not correctly handled when used as a reducer->fixed.
When used as a mapper, was returning nulls when all inputs were equals ->fixed.
> Bug fix in MAD

- warp10/src/main/java/io/warp10/script/ScriptRunner.java
For a detailled explanation on ThreadPoolExecutor, see:
http://www.bigsoft.co.uk/blog/2009/11/27/rules-of-a-threadpoolexecutor-pool-size
> Allow runners to really use runner.nthreads, code cleanup.

- warp10/src/main/java/io/warp10/script/functions/FIND.java
Somewhere in the wild, there is some warpscripts which REXEC "readtoken classname {} FIND", without the LIST nor the MAP syntax. This was working in Warp 10 1.x.
> Fix for retrocompatibility of FIND signature without LIST or MAP.

- warp10/src/main/java/io/warp10/plugins/http/WarpScriptHandler.java
When a macro creates an exception on the initial REQUEST, the handler is called again to handle the ERROR, thus calling the macro twice.
This PR avoid the call of the macro for the ERROR handling.
> Handler now handles only REQUEST to avoid being called twice when there is an error.

- warp10/src/main/java/io/warp10/script/binary/DIV.java
- warp10/src/main/java/io/warp10/script/binary/MUL.java
- warp10/src/main/java/io/warp10/script/binary/SUB.java
Makes error message clearer.
Example:
```NEWGTS 'a' /```
- without PR returns:
`java.lang.String cannot be cast to java.lang.Number`
- with this PR returns:
`/ can only operate on numeric values or Geo Time Series .`
> Add type check to */- operations involving a GTS and a value.

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Fix the output when applying a multiple output macromapper on a bucketized serie. The empty original serie is not returned anymore among the results.
It does not change the default behavior of classic mappers (list output). 
new unit tests ready if accepted.
> Fix mapper output

- warp10/src/main/java/io/warp10/script/formatted/FormattedWarpScriptFunction.java
use getSimpleName() instead of  getCanonicalName() in error messages
> improve error message for type or argument in formatted functions

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Commit 55be372 removed a sanity check l.1521 of GTSHelper in method subSerie().
This sanity check did prevent two cases of ticks being added to a subgts:
-  when stoptimestamp < starttimestamp
- if stoptimestamp is not present in gts, lastidx was wrong by +1
We fix those bugs
> bugfix subserie

- token/src/test/groovy/io/warp10/token/test/TestReadToken.groovy
- token/src/test/groovy/io/warp10/token/test/TestWriteToken.groovy
64 code indices are encoded by more characters. We replace incrementing by decrementing in the tests since incrementing sometimes provoke a collision
> Fix some unit tests

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/script/functions/CHUNK.java
- warp10/src/main/java/io/warp10/script/functions/CHUNKENCODER.java
- Fix missing overlap for first and last chunk of GTSs.
- Removes useless and buggy code for chunks on GTSs.
- Fix bug with chunks of GTSEncoder when keeping empty chunks.
- Changed from TreeMap to HashMap for chunks(GTSEncoders) because ordering was not needed.
- Imports cleaning, typos fixes, more comments.
> Fixes to chunks methods and cleaning of WS functions.

- warp10/src/main/java/io/warp10/script/functions/PACK.java
- warp10/src/main/java/io/warp10/script/functions/UNPACK.java
Parsing when using B could fail, like this script `[ T ] 'B' PACK`
U for PACK is equivalent to L but it makes it easier to use the same format for PACK and UNPACK.
Tested using:
```
[
RAND
RAND
RAND 1e6 *
RAND 1e6 *
RAND 1e60 *
RAND 1e60 *
RAND 1e6000 *
RAND 1e6000 *
Infinity
Infinity
NaN
NaN
15
15
MAXLONG
MINLONG
MAXLONG
MINLONG
MAXLONG
MAXLONG
-15
-15
31
31
42
F
42
T
42
F
42
T
T
]
'data' STORE
'<D>D<D>D<D>D<D>D<D>D<D>D<U4s7>U4<L<LS9>L>L>U<U>L5s1<L5<U5>U5<LBS77>LB<LB>LBB' 'format' STORE
$data $format PACK $format UNPACK
$data 2 ->LIST ZIP
<%
DROP
LIST-> DROP
==
%>
LMAP
AND ASSERT
```
> Fix pack parsing for booleans, factorize parsing, allow U for PACK.

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Makes the equality between GTSs much easier.
No WarpScript function exposing this yet.
> Add a method to fully sort a GTS using tick, value, location, elevation.

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/continuum/gts/GTSOpsHelper.java
- warp10/src/main/java/io/warp10/script/binary/BitwiseAND.java
- warp10/src/main/java/io/warp10/script/binary/BitwiseOR.java
- warp10/src/main/java/io/warp10/script/binary/BitwiseOperation.java
- warp10/src/main/java/io/warp10/script/binary/BitwiseXOR.java
- warp10/src/main/java/io/warp10/script/binary/ComparisonOperation.java
- warp10/src/main/java/io/warp10/script/binary/CondShortCircuit.java
- warp10/src/main/java/io/warp10/script/binary/EQ.java
- warp10/src/main/java/io/warp10/script/binary/GE.java
- warp10/src/main/java/io/warp10/script/binary/GT.java
- warp10/src/main/java/io/warp10/script/binary/LE.java
- warp10/src/main/java/io/warp10/script/binary/LT.java
- warp10/src/main/java/io/warp10/script/binary/NE.java
- warp10/src/main/java/io/warp10/script/binary/SHIFTLEFT.java
- warp10/src/main/java/io/warp10/script/binary/SHIFTRIGHT.java
- warp10/src/main/java/io/warp10/script/unary/NOT.java
Fix the fate of boolean GTS operation in Warp 10 2.0 : allow not, and, or, xor on boolean GTS.
Tried to optimize NOT with flip operation, but I didn't test performances.
I choose to implement and or xor bitwise operators, not condition ones... I can change.
> boolean, bitwise and comparison operators on GTS

- warp10/src/main/java/io/warp10/script/processing/image/Pdecode.java
The pixel per pixel test was a workaround. A more efficient one is to always set to ARGB. It is consistent with Pgraphics, where we always set ARGB:
```java
pg.image = new BufferedImage(pg.pixelWidth, pg.pixelHeight, BufferedImage.TYPE_INT_ARGB);
```
> Pdecode from bytes

- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
`labels` is not used anywhere and there is no side effect in the `put`.
Is `labels` really useless or should it be used somewhere?
> Remove dead code

- warp10/src/main/java/io/warp10/standalone/Warp.java
- warp10/src/main/sh/warp10-standalone.sh
When the address is already in use (BindExection) the server doesn't stop and there is no error message from the terminal.
Stop the server on BindException
Fix use of isStarted function
> Stop the server when address is already in use.

- warp10/src/main/java/io/warp10/continuum/egress/EgressExecHandler.java
- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/aggregator/StandardDeviation.java
- warp10/src/main/java/io/warp10/script/binary/CondShortCircuit.java
- warp10/src/main/java/io/warp10/script/ext/token/TOKENSECRET.java
- warp10/src/main/java/io/warp10/script/functions/EXPORT.java
- warp10/src/main/java/io/warp10/script/functions/FOR.java
- warp10/src/main/java/io/warp10/script/functions/FOREACH.java
- warp10/src/main/java/io/warp10/script/functions/FORSTEP.java
- warp10/src/main/java/io/warp10/script/functions/IFT.java
- warp10/src/main/java/io/warp10/script/functions/IFTE.java
- warp10/src/main/java/io/warp10/script/functions/LFLATMAP.java
- warp10/src/main/java/io/warp10/script/functions/LMAP.java
- warp10/src/main/java/io/warp10/script/functions/MACROCONFIGSECRET.java
- warp10/src/main/java/io/warp10/script/functions/SETMACROCONFIG.java
- warp10/src/main/java/io/warp10/script/functions/SWITCH.java
- warp10/src/main/java/io/warp10/script/functions/UNTIL.java
- warp10/src/main/java/io/warp10/script/functions/WHILE.java
- warp10/src/main/java/io/warp10/script/mapper/MapperKernelSmoother.java
`o instanceof SomeClass` returns `false` when `o` is `null` so there is no need to test for nullity before `instanceof`.
This will stay that way as it is in the specs of Java: https://docs.oracle.com/javase/specs/jls/se11/html/jls-15.html#jls-15.20.2
Also fixes the testing of the types in IFTE.
> Do not check nullity when instanceof already does

- warp10/src/main/java/io/warp10/continuum/gts/GTSEncoder.java
- warp10/src/main/java/io/warp10/script/functions/CLIP.java
- warp10/src/main/java/io/warp10/script/functions/CLONEEMPTY.java
- warp10/src/main/java/io/warp10/script/functions/RENAME.java
- warp10/src/main/java/io/warp10/script/functions/SETATTRIBUTES.java
- warp10/src/main/java/io/warp10/script/functions/TICKLIST.java
- warp10/src/main/java/io/warp10/script/functions/TOSELECTOR.java
- warp10/src/main/java/io/warp10/script/functions/VALUES.java
The converted function accepted GTS, GTSEncoders or List of GTSs.
They now also accept List of GTSEncoders.
Also fix a bug in GTSEncoder.cloneEmpty where the metadata was not copied.
> Convert some GTSStackFunctions to ElementOrListStackFunction

- token/src/test/java/io/warp10/token/test/TestReadToken.java
1 ms is too short and throws QuasarFilterUnavailable instead of QuasarTokenExpired
> Fix testTokenExpired

- warp10/src/main/java/io/warp10/script/formatted/FormattedWarpScriptFunction.java
- warp10/src/main/java/io/warp10/script/formatted/ListSpecification.java
- warp10/src/test/java/io/warp10/script/formatted/FormattedWarpScriptFunctionTest.java
First argument of a formatted function can now be defined as "list-expandable".
In this argument is a list, a list of results as though it was applied foreach element of this list is returned.
> Integrate formatted functions into "list or not list" warpscript pattern

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
This fix allows the following to correctly preserve datapoints at tick 0
NEWGTS 'a' RENAME
0 NaN NaN NaN 0 ADDVALUE
0 NaN NaN NaN 10 ADDVALUE
1 NaN NaN NaN 1 ADDVALUE
2 NaN NaN NaN 2 ADDVALUE
NEWGTS 'b' RENAME
0 NaN NaN NaN 2 ADDVALUE
0 NaN NaN NaN 3 ADDVALUE
2 ->LIST
COMMONTICKS
> Fixed commonticks so it correctly copies duplicate ticks

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/script/functions/BUCKETIZE.java
BUCKETIZE can take NULL as a bucketizer, in which case it only sets lastbucket, bucketcount, and bucketspan on the input gts.
> Set lastbucket, bucketcount and bucketspan

- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
Idea: to know exactly what instruction in the line causes the failure.
- Independant of LINEON, there is no cost to do it.
- comments are preserved, long statements are cut to 30 characters (also helps to preserve secrets).
Example:
```java
//will fail
[ 1 ] 0    GET 1 GET 1 GET STOP    'very very very very very very very very long string'  //very very very very very very very very long comment
```
Error message:
`2 in section '[TOP]':  [ 1 ] 0    GET 1 =>GET<= 1 GET STOP    'very%20very%20very%20very%...  //very very very very very very very very long comment  : GET operates on a map, list or byte array.`
Possible enhancement : copy `StringUtils.abbreviate` function somewhere to avoid another import.
> add error location tip into error message

- warp10/src/main/sh/warp10.service
It is a forking unit, not a oneshot with remainAfterExit.
Tested with several level of kill, systemd relaunch warp 10 correctly.
journalctl is now cleaner.
> Systemd unit fix

- warp10/src/test/java/io/warp10/script/formatted/RunAndGenerateDocumentationWithUnitTests.java
RunAndGenerateDocumentationWithUnitTests can be extended.
Makes it easier for an extension to generate documentation and unit tests of formatted functions.
> Formatted 

- warp10/src/main/java/io/warp10/continuum/sensision/SensisionConstants.java
- warp10/src/main/java/io/warp10/continuum/store/Directory.java
- warp10/src/main/java/io/warp10/standalone/StandaloneDirectoryClient.java
In a context of user in Warp10, it can be great to keep trace of the series account per Warp application. 
In this PR, we simply add a Metrics `warp.directory.gts.perapp` directly in the directory.
Written by @StevenLeRoux and me.
> feat(directory): add a gts per app metrics

- etc/conf.templates/distributed/10-directory.conf.template
- etc/conf.templates/distributed/10-egress.conf.template
- etc/conf.templates/distributed/10-ingress.conf.template
- etc/conf.templates/distributed/10-plasma.conf.template
- etc/conf.templates/distributed/30-ssl.conf.template
- etc/conf.templates/distributed/80-http-plugin.conf.template
- etc/conf.templates/standalone/00-warp.conf.template
- etc/conf.templates/standalone/30-ssl.conf.template
- etc/conf.templates/standalone/80-http-plugin.conf.template
- warp10/src/main/java/io/warp10/SSLUtils.java
- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/continuum/egress/Egress.java
- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
- warp10/src/main/java/io/warp10/continuum/plasma/PlasmaFrontEnd.java
- warp10/src/main/java/io/warp10/continuum/store/Directory.java
- warp10/src/main/java/io/warp10/plugins/http/HTTPWarp10Plugin.java
- warp10/src/main/java/io/warp10/plugins/tcp/TCPManager.java
- warp10/src/main/java/io/warp10/standalone/Warp.java
Default values in Kernel and Java are pretty conservative. When scaling, those parameters cause some SYN requests to be dropped without notice.
JVM default value is 50.
Effective value (ss -ltpn) is the minimum between supplied value and net.core.somaxconn.
> Add parameters about Listen Queue/Backlog in TCP

- warp10/src/main/sh/warp10-standalone.sh
"if" statement from line 66 was unreachable in case it would be false since "set -euo pipefail" was inserted at the begining of the script.
With -e option, if egrep command fails then the script exits immediately, except if it is put in a conditional statement.
> minor bugfix error message warp10-standalone.sh

- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
` 2 0 /` raise the error : `Exception at '2 0 =>/<=' in section [TOP] (/ by zero)`
` '2 0 /' EVAL` raise the error : `Exception at ''2%200%20/' =>EVAL<=' in section [TOP] (Line #1: Exception at '2 0 =>/<=' in section [TOP])` You do not know what goes wrong.
With this fix, which might not be the best, the error message is now:
` '2 0 /' EVAL` raise the error : `Exception at '"2%200%20/" =>EVAL<=' in section [TOP] (io.warp10.script.WarpScriptException: Exception at '2 0 =>/<=' in section [TOP] (Exception at '2 0 =>/<=' in section [TOP] (/ by zero)))`
> Exception detail in EVAL

- warp10/src/main/java/io/warp10/script/functions/HYBRIDTEST2.java
HYBRIDTEST2 needs that input bucketized GTS is filled
> HYBRIDTEST2 bugfix

- warp10/src/main/java/io/warp10/script/functions/SNAPSHOT.java
This PR adds the possibility to register custom SNAPSHOT encoders which can handle types otherwise not handled by the standard SNAPSHOT function,
> Added support for additional SNAPSHOT encoders

- warp10/src/main/java/io/warp10/script/formatted/FormattedWarpScriptFunction.java
Makes it easier for extensions to design abstract formatted warpscript functions (then append arguments of child class).
> add argument to Arguments builder using specification

- warp10/src/main/sh/warp10-standalone.sh
Allow to log errors in warp10.log, and also to have them in systemd logs when installed as a service.
Follow tutorial [here](https://www.warp10.io/content/03_Documentation/02_Installation/01_Standalone#autostart), then try `journalctl -f -u warp10` 
Usefull when warp10 fails to start, or with STDERR WarpScript function.
> duplicate stderr to logs and stderr for process journal

- warp10/src/main/java/io/warp10/script/aggregator/Median.java
TLDR: Median aggregator must always return a double to avoid confusion. 
A wildly accepted definition of the median, [as on NIST](https://www.itl.nist.gov/div898/handbook/eda/section3/eda351.htm), makes it so the median of an even number of elements is the mean of two elements. This means the median has a probability of 1 of being a floating point number for a list of floating point number and a probability of 0.25 of being a floating point number for a list of integers (0.5 the list has an odd number of elements, 0.25 the list has an even number of elements and the difference between the two elements use to compute the mean is even and 0.25 the list has an even number of elements and the difference between the two elements use to compute the mean is odd). The simplest solution is thus to …
> Make median aggregator always return a double.

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/script/functions/MAP.java
Avoid MAP to silently overflow on `occurrences`.
> MAP to accept abs(occurrences)>Integer.MAX_VALUE and code simplification.

- warp10/src/main/java/io/warp10/script/functions/STORE.java
Bug fix. Because you may write 'foo' [ 'bar' ] STORE
> STORE bug fix for singleton list

- etc/log4j.properties
- fix  #694 by appending plugin and extension loading messages to stdout. 
- "warpscript.events" logger was created on purpose in egress execution, but was not used as it should be, or may have been. (warpscript.out remains empty)
- fix additivity to avoid double logs.
Didn't touch hadoop and zookeeper parts...
> set log4j properties to fix #694

- warp10/src/main/java/io/warp10/script/functions/FETCH.java
- warp10/src/main/java/io/warp10/standalone/WarpRepair.java
When using the 'gts' parameter of the FETCH input map, we now perform some more advanced checks to ensure that the provided READ token would actually select the given GTS. We also replace somme labels (namely owner or producer) if absent by a value extracted from the token and which makes the GTS fall within the set of GTS which could be selected with the given token.
> Modified validation of GTS list.

- etc/conf.templates/distributed/00-warp.conf.template
- etc/conf.templates/standalone/00-warp.conf.template
- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/continuum/Tokens.java
Add the ability to define a list of token attributes which are banned. Any token bearing one of those attributes will be rejected with an error by the standard token parsing code.
The ability to disable those checks is offered so authentication plugins can rely on token extraction even if the token is bearing a banned attribute.
> Attribute check for tokens

- build.gradle
- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/functions/FETCH.java
- warp10/src/main/java/io/warp10/script/functions/NOTAFTER.java
- warp10/src/main/java/io/warp10/script/functions/NOTBEFORE.java
- warp10/src/main/java/io/warp10/script/functions/TIMECLIP.java
- warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java
This is to reflect the fact that already a lot of code is only compatible with Java 8+, mainly because of ` Math.*Exact()` and `Files.walk()`.
> Set the source and target to Java 8, making this project only support Java 8+.

- warp10/src/main/java/io/warp10/script/mapper/MapperDateTime.java
- warp10/src/main/java/io/warp10/script/mapper/MapperDayOfMonth.java
- warp10/src/main/java/io/warp10/script/mapper/MapperDayOfWeek.java
- warp10/src/main/java/io/warp10/script/mapper/MapperHourOfDay.java
- warp10/src/main/java/io/warp10/script/mapper/MapperMinuteOfHour.java
- warp10/src/main/java/io/warp10/script/mapper/MapperMonthOfYear.java
- warp10/src/main/java/io/warp10/script/mapper/MapperSecondOfMinute.java
- warp10/src/main/java/io/warp10/script/mapper/MapperYear.java
Previously those mappers accepted any parameter and defaulted to UTC. Now throw if it is not a valid timezone or offset.
> Factorize mappers using DateTime and fail for invalid TimeZone or offset.

- warp10/src/main/java/io/warp10/WrapperList.java
- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
- warp10/src/main/java/io/warp10/script/WarpScriptStack.java
- warp10/src/main/java/io/warp10/script/functions/STACKTOLIST.java
- warp10/src/main/java/io/warp10/script/functions/TOLIST.java
- warpscript/build.gradle
When `Stack.popn()` is called, it copies the requested elements in the stack array in a new array. In `TOLIST`, this new array is wrapped in a `List` using `Arrays.asList`, which does not copy the data. However when using either `addAll` or the `ArrayList` constructor, it calls `toArray()` on the wrapped array which does a `clone`. 
This PR avoids this last unneeded copy by assigning directly the array produced by `popn()` to the internal array of the `ArrayList`. It also uses `System.arraycopy` which is much faster.
Perf gains expressed as % of time taken for a `->LIST` using the PR code wrt the pre-PR code ie _100 * time_pr / time_pre_pr_.
| Number of elements  | % time taken |
| ------------- | ------------- |
| 1 | 60%  |
| 10  | 65%  |
| 100 | 45%  |
| 1000  | 14%  |
| 10000 | 11%  | …
> Avoid a copy when building List from stack

- warp10/src/main/java/io/warp10/script/ext/shm/SharedMemoryWarpScriptExtension.java
- warp10/src/main/java/io/warp10/script/functions/ASREGS.java
- warp10/src/main/java/io/warp10/standalone/StandaloneMemoryStore.java
- SHM lock used SHM stored object instead of associated mutex name
- ASREGS could simpply use already stored and type-checked key
- StandaloneMemoryStore, although rarely used, used value instead of key to remove entries
> Fix get/remove on Maps with wrong keys or replace with simplier parameter

- warp10/src/main/java/io/warp10/script/WarpScriptMacroRepository.java
Move checks on `name` later to avoid NPE if `null == name`.
> Change checks order to really make name optional

- warp10/src/main/java/io/warp10/script/functions/ASREGS.java
- warp10/src/main/java/io/warp10/script/functions/VARS.java
Simplifies `DUP VARS ASREGS` to `ASREGS`.
When ASREGS is not given a list of symbol names it will use all those defined in the macro.
To do that, the PR extracts the logic of VARS in a static function for ASREGS to use it.
> Make list of symbol names optional for ASREGS

- warp10/src/main/java/io/warp10/script/functions/FETCH.java
- warp10/src/main/java/io/warp10/script/functions/FIND.java
As it is possible to fetch using both count and timespan, limits are applied even if the bounded parameters are not set.
It is also possible to fetch without a timespan(using only start and end) which resulted in a NPE before this PR.
It should be possible to allow preboundary and postboundary according to which limits are sets, the simpler case, for instance, is when no limit is set.
> Make metaset easier to use and avoid NPE when fetching without timespan

- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
- warp10/src/main/java/io/warp10/script/functions/MAXDEPTH.java
```
10 MAXDEPTH // Default size of the element backing MemoryWarpScript is 32
1 20
<% %>
FOR // Will fail with this PR but not without
```
> Fix case where MAXDEPTH is smaller than the array backing the stack

- warp10/src/main/java/io/warp10/script/functions/TYPEOF.java
An interface that extends typeofable will fail on "getDeclaredConstructor".
A typeResolver can be added by the extension that uses this interface to answer this.
> Try type resolver if typeofable fails

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/script/functions/DEDUP.java
This optional parameter can apply more complex strategies for merging duplicate ticks than just keeping the last tick.
The implementation is based on GTSHelper.map but does not expose this parameter in MAP. This is because deduping will behave strangely with step>1, pre>0, post>0 or when using outputTicks. This is why it was included in DEDUP and not MAP.
Example:
```
NEWGTS
0 NaN NaN NaN 0 ADDVALUE
1 NaN NaN NaN 1 ADDVALUE
1 NaN NaN NaN 2 ADDVALUE
1 NaN NaN NaN 3 ADDVALUE
2 NaN NaN NaN 4 ADDVALUE
3 NaN NaN NaN 5 ADDVALUE
mapper.median DEDUP
```
Gives
```
[[{"c":"","l":{},"a":{},"la":0,"v":[[0,0.0],[1,2.0],[2,4.0],[3,5.0]]}]]
```
> Add optional macro or mapper parameter for DEDUP to merge duplicate ticks

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/functions/TOGEOJSON.java
- warp10/src/main/java/io/warp10/script/functions/TOWKB.java
- warp10/src/main/java/io/warp10/script/functions/TOWKT.java
Modifies ->GEOJSON to convert WKT and WKB to GEOJSON.
Adds ->WKT and ->WKB to convert GEOJSON, WKT and WKB to WKT and WKB respectively.
For now, ->WKT and ->WKB cannot convert a GEOSHAPE to WKT and WKB. Three solutions:
- We leave as it is, it the user want to do that, he/she converts first to GEOJSON and then to WKT/WKB
- ->WKT and ->WKB function internally convert to GEOJSON and then to the desired output format (easier for the user)
- Add methods in GeoXPLib to convert a Coverage to WKT or WKB (this one is trickier) and use that in the fonctions.
> Add conversion between GeoJSON, WKT and WKB formats

- warp10/src/main/java/io/warp10/json/BytesSerializer.java
- warp10/src/main/java/io/warp10/json/GTSEncoderSerializer.java
- warp10/src/main/java/io/warp10/json/JsonUtils.java
- warp10/src/main/java/io/warp10/json/MacroSerializer.java
- warp10/src/main/java/io/warp10/json/MetadataSerializer.java
Current custom JSON serialization is not working and could be more practical.
#798 proposed to expose Jackson API but it is preferable not to in case we want to change the JSON serialization/deserialization library.
This PR changes the current API to register custom serialization, making it simpler to use while not exposing Jackson.
The idea is to allow the registration of "transformers" whose role is to convert un-serializable objects to serializable ones. Typically they will create a Map corresponding to the fields of the Object.
Example of use:
```
JsonUtils.addTransformer(new JsonUtils.JsonTransformer() {
@Override
public TransformationResult transform(Object o) {
if (o instanceof CustomObject) {
HashMap<String, Object> coRepresentation = new HashMap<String, Object>(); …
```
> Modify custom JSON serialization

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Original code is
```
if (0 == chunkgts.values) {
GTSHelper.shrink(chunkgts);
} else if (overlap <= 0 && gts.values > 0 && chunkgts.ticks.length - chunkgts.values > 0) {
GTSHelper.shrink(chunkgts);
} else if (overlap > 0 && chunkgts.values > 0 && chunkgts.ticks.length - chunkgts.values > 2 * overlaphint) {
GTSHelper.shrink(chunkgts);
}
```
Fix `gts.values` to `chunkgts.values`
When `overlap <= 0`, we have `0 == overlaphint` so we can convert the code above to
```
if (0 == chunkgts.values) {
GTSHelper.shrink(chunkgts);
} else if (overlap <= 0 && chunkgts.values > 0 && chunkgts.ticks.length - chunkgts.values > 2 * overlaphint) {
GTSHelper.shrink(chunkgts);
} else if (overlap > 0 && chunkgts.values > 0 && chunkgts.ticks.length - chunkgts.values > 2 * overlaphint) {
GTSHelper.shrink(chunkgts); …
```
> Fix and simplify condition for shrink in GTSHelper#chunk

- warp10/src/main/java/io/warp10/script/binary/ComparisonOperation.java
Currently only
```
NEWGTS 1 NaN NaN NaN 1 ADDVALUE
1
==
```
is valid.
This PR also allows
```
1
NEWGTS 1 NaN NaN NaN 1 ADDVALUE
==
```
> Allow comparison functions to take both gts op and op gts

- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
This reduce a bit the time to copy registers when doing a SAVE/RESTORE.
> Speed up restore with System.arraycopy on registers

- crypto/src/main/java/io/warp10/crypto/KeyStore.java
- warp10/src/main/java/io/warp10/script/ScriptRunner.java
`SIPHASH_KAFKA_PLASMA_FRONTEND_OUT` and `AES_KAFKA_PLASMA_FRONTEND_OUT` are not used because Plasma FE does not produce anything on Kafka.
`AES_KAFKA_RUNNER` is not used because the key which is really used is called `RUNNER_PSK`.
> Remove unused keys in keystore

- warp10/src/main/java/io/warp10/standalone/StandaloneChunkedMemoryStore.java
- warp10/src/main/java/io/warp10/standalone/StandaloneMemoryStore.java
`encoder.getMetadata()` always returns a non-null `Metadata` instance so there's non need to check for nullity.
> Remove unneeded check because metadata is always non-null

- warp10/src/main/java/io/warp10/continuum/egress/EgressFetchHandler.java
- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
Use ThreadLocalRandom to avoid contention instead of a static Random instance.
> Do not instantiate a new Random each time a onetimepad is created

- warp10/src/main/java/io/warp10/script/functions/SORTBY.java
The current logic with doubles fails with NaN or -0.0.
Also simplifies the code for longs.
The script
```
[
0.0
NaN
-1.0
1.0
-0.0
]
<% %>
SORTBY
[
0.0
NaN
-1.0
1.0
-0.0
]
LSORT
```
Returns before PR
`[[-1.0,-0.0,0.0,1.0,NaN],[0.0,NaN,-1.0,-0.0,1.0]]`
and after PR:
`[[-1.0,-0.0,0.0,1.0,NaN],[-1.0,-0.0,0.0,1.0,NaN]]`
> Fix comparator to behave correctly with NaN and -0.0

- warp10/src/main/java/io/warp10/WarpConfig.java
- warp10/src/main/java/io/warp10/WarpDist.java
- warp10/src/main/java/io/warp10/standalone/Warp.java
- warp10/src/main/java/io/warp10/worf/TokenGen.java
- warp10/src/main/java/io/warp10/worf/Worf.java
- warp10/src/main/sh/warp10-standalone.sh
This should avoid any problem with functions using default encoding used throughout the code:
- new String(byte[])
- new PrintWriter
- new InputStreamReader
- new OutputStreamWriter
- etc.
> Set UTF-8 as default encoding and check it is at the start of Warp 10

- warp10/src/main/java/io/warp10/script/functions/SPLIT.java
Performance is the same when used without limit.
With limit, the performance can be increased, for instance:
```
UUID '-' 2 SPLIT 0 GET // Faster
UUID '-'   SPLIT 0 GET // Slower
```
> Add a limit parameter to SPLIT

- warp10/src/main/java/io/warp10/script/ext/shm/SHMDEFINED.java
- warp10/src/main/java/io/warp10/script/ext/shm/SHMLOAD.java
- warp10/src/main/java/io/warp10/script/ext/shm/SHMSTORE.java
- warp10/src/main/java/io/warp10/script/ext/shm/SharedMemoryWarpScriptExtension.java
Currently, to check if a SHM symbol exists, we have to use `SHMLOAD` and `TRY` to catch the exception if the symbol is not defined. This strategy has to be used everywhere as the symbol may have expired because of the TTL.
This "better ask for forgiveness than permission" method is usually not the way to go in Java and thus in WarpScript. `SHMDEFINED` used in conjunction with `IFT` fixes that. When the symbol does not exist, this method is ~5x faster, when it exists, it is marginally slower.
> Add SHMDEFINED which tells if a symbol is defined in SHM

- warp10/src/main/java/io/warp10/standalone/StandaloneDirectoryClient.java
`classids` was a `HashMap` which is not thread safe although it is accessed by several threads. In particular, it resulted in `CLASS_COMPARATOR` to fail with NPE because the `get` couldn't find the key because of a concurrent `put`.
Also `unregister` is not synchronized anymore because it was the only synchronized method and no synchronization on `this` was done. On the contrary, critical parts are synchronized on `metadatas`, so the critical part in `unregister` is now synchronized on `metadatas` as well.
> Fix concurrency in StandaloneDirectoryClient

- warp10/src/main/java/io/warp10/script/functions/ALMOSTEQ.java
One of the operand had to be a double, which is not required by the code. Removed that.
**Be careful**: the comparison with `lambda` was strict, which is not what users could expect. For instance, `1 1 0 ~=` would return `false`. Changed that also.
> ALMOSTEQ (~=): Make conditions on parameters less strict

- warp10/src/main/java/io/warp10/script/functions/SORTWITH.java
Before this PR, STOP in a SORTWITH macro wouldn't work as expected.
> Fix SORTWITH to throw ATC exceptions instead of catching them.

- token/src/main/java/io/warp10/quasar/encoder/QuasarTokenEncoder.java
- warp10/src/main/java/io/warp10/continuum/Tokens.java
- warp10/src/main/java/io/warp10/script/ext/token/TOKENDUMP.java
- warp10/src/main/java/io/warp10/script/ext/token/TOKENGEN.java
- warp10/src/main/java/io/warp10/script/ext/token/TokenWarpScriptExtension.java
This PR allows the signatures
```
$map $aes $hash TOKENGEN
$token $aes $hash TOKENDUMP
```
to be used in any configuration, without secret.
If AES and SipHash keys are not specified, the behavior is the same as before, ie if keystore is that of a Warp/WarpDist instance, a secret is mandatory both in the conf and in the signatures, else no secret is necessary.
Also fixed a potential bug with non-thread safe `TSerializer` and improved error messages.
> Allow TOKENGEN and TOKENDUMP to be used always on custom keys without secret

- warp10/src/main/java/io/warp10/plugins/http/HTTPWarp10Plugin.java
- warp10/src/main/java/io/warp10/plugins/http/WarpScriptHandler.java
On 100s MB files, there is no noticeable difference in speed between the previous method (all the data in the request payload) and the stream method. However, the memory consumption of the stream method is, as expected, lower.
Example of a script to read [IBTrACS](https://www.ncdc.noaa.gov/ibtracs/) CSV files by splitting the stream on new lines.
```
{
'path' '/ibtracs'
'prefix' false
'streamDelimiter' '%0A' 'UTF-8' ->BYTES
'macro' 
<% 
'payload' STORE
'request' STORE
$payload ISNULL NOT
<% 
$payload 'UTF-8' BYTES->
'row' STORE
<%
$row ',' 13 SPLIT
'row_split' STORE
$row_split 0 GET 'id' STORE
$row_split 6 GET TRIM ' ' 'T' REPLACE 'z' +
TOTIMESTAMP 'ts' STORE
$row_split 8 GET TODOUBLE 'lat' STORE
$row_split 9 GET TODOUBLE 'lon' STORE
$row_split 10 GET TRIM
DUP SIZE 0 >
<% TODOUBLE %>
<% …
```
> Add streamDelimiter parameter to HTTP definitions to stream the POST payload to the macro

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/script/functions/PARSEVALUE.java
Allows more precise message for parsing errors, mostly useful for debugging multivalues errors.
Executing
```
<'
1// a{} [ 1 [ [ hex:1 ] ] ]
'>
PARSE
```
gives `Exception at '=>PARSE<=' in section [TOP] (PARSE could not parse at index 16 in '1// a{} [ 1 [ [ hex:1 ] ] ]' (Cannot parse value. (Odd number of hexadecimal digits.)))`
Executing
```
<'
[ 1 [ [ hex:1 ] ] ]
'>
PARSEVALUE
```
gives `Exception at '=>PARSEVALUE<=' in section [TOP] (PARSEVALUE encountered a parse error at index 8 for '[ 1 [ [ hex:1 ] ] ]'. (Cannot parse value. (Odd number of hexadecimal digits.)))`
Sending
```
curl -H "X-Warp10-Token:WRITETOKEN" --data-binary "1// a{} [ 1 [ hex:1 ] ]" http://127.0.0.1:8080/api/v0/update
```
gives `Error when updating data: Parse error at index 14 in &apos;1// a{} [ 1 [ hex:1 ] ]&apos; …
> More precise offset for ParseException thrown by GTSHelper.parseValue

- warp10/src/main/java/io/warp10/WarpConfig.java
- warp10/src/main/java/io/warp10/WarpDist.java
When a configuration file contain errors (multiple `=` or invalid url-encoding), starting Warp 10 produces a message similar to this:
`Found errors while reading /opt/warp10/etc/conf.d/70--extensions.conf. (Malformed lines [61, 80].)`
Fixes #872.
> Precise error message when conf files contain invalid lines, fixes #872

- warp10/src/main/sh/warp10-standalone.sh
Do not call WarpInit when starting Warp 10 in memory.
> Disable WarpInit with in memory mode to avoid IO error with LevelDB.

- etc/conf.templates/standalone/30-in-memory.conf.template
- warp10/src/main/java/io/warp10/standalone/Warp.java
Non-chunked memory store has been deprecated for a long time now. Thus, it is reasonable to make chunked memory store a default in the configuration file.
Also make comment clearer and fix typo.
> Make memory store chunked by default in the conf file

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/processing/image/Presize.java
- warp10/src/main/java/io/warp10/script/processing/image/Psize.java
- warp10/src/main/java/io/warp10/script/processing/rendering/PGraphics.java
With a very large Warp 10 logo scaled to 1/20:
Only `Pimage`:
`'ADD' Pblend` on a black background:
`Preszie` + `Pimage`:
> Add Presize for bilinear resizing and small fixes

- warp10/src/main/java/io/warp10/WarpConfig.java
I had debug code which used `setProperties((String)null))` which fails because of #875. On my JVM (OpenJDK 1.8.0_275), the varargs results in an array with a single `null` filename, which makes the code fail.
It is unclear if `null` given to a varargs method in Java results in a `null` array or an array with a single `null` element. Check both cases to make sure.
Also removed `readConfig(new StringReader(""), properties);` which does not do anything because
```
envVarsAndSysPropsOverride();
expandVars(exitOnError);
checkAndInit();
```
have been extracted from the `readConfig` method in #875.
> Add nullity checks for filenames in WarpConfig#setProperties

- warp10/src/main/java/io/warp10/script/WarpScriptMacroRepository.java
- warp10/src/main/java/io/warp10/script/functions/MACROTTL.java
Other hard values were checked in MacroLibrary and in the WarpFleet resolver, this PR moves all hard value checks where the macro ttl attribute value is actually used.
> Moved the hard value check in WarpScriptMacroRepository

- etc/conf.templates/distributed/00-secrets.conf.template
- etc/conf.templates/standalone/00-secrets.conf.template
- etc/conf.templates/standalone/10-leveldb.conf.template
These keys were spotted by @pi-r-p in https://github.com/senx/warp10-platform/pull/863#issuecomment-760789122
> Remove deprecated configuration keys from templates

- warp10/src/main/java/io/warp10/standalone/WarpDB.java
Removed the stack trace because it gave the impression that Warp 10 failed to start or started in a bad state.
Instead change the log a bit so that for a `UnsatisfiedLinkError` it produces:
`WARN  standalone.WarpDB - Falling back to pure java implementation of LevelDB because: Native LevelDB implementation disabled.`
and for a `NoClassDefFoundError` it produces:
`WARN  standalone.WarpDB - Falling back to pure java implementation of LevelDB because: Could not load library. Reasons: [no leveldbjni64-2.7.2-39-g0b1bfad7 in java.library.path, no leveldbjni-2.7.2-39-g0b1bfad7 in java.library.path, no leveldbjni in java.library.path]`
> Remove stacktrace and add clearer error message

- warp10/src/main/sh/warp10-standalone.sh
Fixes #874 
`set -u` does not seems to pose any problem, but I only tested on Ubuntu 20.04. 
```
JAVA_OPTS=${JAVA_OPTS:-}
```
Seems to indicate `set -u` could pose problem with default values.
> Add default value to $1 to avoid unbound variable error if no parameter

- etc/conf.templates/standalone/10-leveldb.conf.template
- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/standalone/Warp.java
This can simplify tests, for instance, when tests have to be done on an empty LevelDB.
I'm not sure it should replace WarpInit however, because WarpInit makes additional checks (verifyChecksums and paranoidChecks).
> Add LevelDB createIfMissing Warp 10 configuration

- token/src/test/java/io/warp10/token/test/TestWriteToken.java
The `testTokenExpired` fails sometimes because:
- The token is created with `issuance = System.currentTimeMillis()` and `ttl = 1 ms`.
- A sleep of 1 ms is done
- The validity of the token is checked with `(issuance + ttl) < System.currentTimeMillis()` which fails sometimes, because `(issuance + ttl) == System.currentTimeMillis()`
> Fix token expiry test

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/WarpScriptReturnException.java
- warp10/src/main/java/io/warp10/script/functions/BREAK.java
- warp10/src/main/java/io/warp10/script/functions/CONTINUE.java
- warp10/src/main/java/io/warp10/script/functions/NRETURN.java
- warp10/src/main/java/io/warp10/script/functions/RETURN.java
- warp10/src/main/java/io/warp10/script/functions/TIMESPLIT.java
For a script containing only `CONTINUE` the error message is currently `CONTINUE`.
This PR changes it to `Exception at CONTINUE: must be used in a one of FOR, FOREACH, FORSTEP, WHILE, UNTIL loop.`
This is more informative than what we have currently but less than what we get for other WarpScriptException. Having the same level of information will probably have a negative impact on the performance on the use of WarpScriptATCException so this PR might be the right balance.
`CONTINUE` and `BREAK` now use a single Exception instance which is better in terms of performance but makes the display of the stack trace impossible. I'm not sure if it is problematic or not.
`RETURN` and `NRETURN` has also been merged and the `NRETURN` class is marked as deprecated, but not the function.
Some useless …
> Uniformize and improve error messages for ATC Exceptions

- warp10/src/main/java/io/warp10/continuum/egress/EgressMobiusHandler.java
- warp10/src/main/java/io/warp10/continuum/ingress/IngressStreamUpdateHandler.java
- warp10/src/main/java/io/warp10/standalone/StandalonePlasmaHandler.java
- warp10/src/main/java/io/warp10/standalone/StandaloneStreamUpdateHandler.java
Throwing an exception in a `@OnWebSocketMessage` method result in a Jetty error:
```
Cannot call method public void io.warp10.standalone.StandaloneStreamUpdateHandler$StandaloneStreamUpdateWebSocket#onWebSocketMessage(org.eclipse.jetty.websocket.api.Session, java.lang.String) with args: [org.eclipse.jetty.websocket.common.WebSocketSession, java.lang.String]
```
It seems the correct way is to close the session with a status code and an error message, which is what this PR does.
> Better handling of errors in websockets

- warp10/src/main/java/io/warp10/script/functions/DEDUP.java
When `DEDUP` is used with an aggregator or a macro (new in 2.7.0), it always generates a list of GTSs for each GTS. This is because this function is very similar to `MAP` so aggregators/macros can generate several GTSs. However, in the case the aggregator/macro returns a single GTS, `MAP` does not nest lists for simplicity.
This PR aims at replicating this behavior in `DEDUP`, avoiding list nesting when possible.
This does change the signature of `DEDUP`, however as this functionality is rather new and is already [documented as avoiding nesting](http://warp10.io/doc/DEDUP), this change may be considered as acceptable.
Signatures without this PR:
`GTS AGGREGATOR/MACRO` **`DEDUP`** `LIST<GTS>`
`LIST<GTS> AGGREGATOR/MACRO` **`DEDUP`** `LIST<LIST<GTS>>`
Signatures with this PR:
For an …
> Fix DEDUP signature so that it reduces list nesting

- warp10/src/main/java/io/warp10/script/ext/shadow/ShadowWarpScriptExtension.java
Macros which leave something on the stack will make the `restore` fail, fixing that.
> Fix Shadow context save and restore

- warp10/src/main/java/io/warp10/standalone/InMemoryChunkSet.java
`hint` could be negative when count is large because of an overflow. This PR handles the overflow.
Also added the postBoundary to the count to have a more precise estimation of the encoder size.
> Avoid overflow of the encoder estimated size

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/functions/SNAPSHOT.java
- warp10/src/main/java/io/warp10/script/processing/Pencode.java
This PR adds:
- PGraphics
- PImage
- RealVector
- RealMatrix
- Matcher
- PShape (using reflection)
Types that can be created with core WarpScript that are still unhanded:
- PFont because it does not contain enough information to recreate the font with `PcreateFont` like the URI.
- StackContext because it could expose defined functions.
> Make more types snapshotable

- warp10/src/main/java/io/warp10/script/processing/typography/PcreateFont.java
The documentation specifies that the size is optional and the online font case (line 92) does handle that case with a default of 12 size font.
> PcreateFont: Fix parameter handling to allow for default 12 size

- warp10/src/main/java/io/warp10/script/functions/IMMUTABLE.java
Doc and comment specify that `Map` is handled but it was not.
Does not use `unmodifiableCollection` else it will make all checks on `List` and `Set` types fail.
> Fix IMMUTABLE to handle Map and return correct type

- warp10/src/main/java/io/warp10/script/MacroHelper.java
- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
- warp10/src/main/java/io/warp10/script/NamedWarpScriptFunction.java
- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/WarpScriptStack.java
- warp10/src/main/java/io/warp10/script/functions/FUNCREF.java
- warp10/src/main/java/io/warp10/script/functions/SNAPSHOT.java
This is an attempt to improve the snapshot of `WarpScriptStackFunctions` and `NamedWarpScriptFunctions` for https://github.com/senx/warp10-platform/pull/945.
This also solve a bug with the snapshots of `WarpScriptStackFunctions` whose reference is on the stack, using `NPDF` for instance. `42 mapper.gt` does not trigger the bug because it is only a `NamedWarpScriptFunction`.
Tested using:
```
42 mapper.gt 'M' STORE
0 1 NPDF 'N' STORE
<%
'Hello' 42 
53 SQRT
42 mapper.gt
!$M
0 0 1 NPDF EVAL
0 !$N
%>
'macro' STORE
// Macro snapshot and EVAL
$macro
SNAPSHOT
EVAL
EVAL
// Snapshot of MACRO-> and EVAL
$macro
MACRO->
SNAPSHOT
EVAL
->MACRO
EVAL
// EVAL of the macro to check the results
@macro
```
> Add FUNCREF and improve snapshots of WarpScriptStackFunctions

- warpscript/build.gradle
Following https://github.com/senx/warp10-platform/commit/82a19b8a8c733703b1dbf870c43313c9c34434ed the JTS lib which Warp 10 depends on is `jts-core` and not `jts` anymore.
As `com.geoxp:geoxplib` pulls jts and `com.geoxp:geoxplib` pull jts-core, the WarpScript lib is already working properly.
> Fix required lib for WarpScript

- warp10/src/main/java/io/warp10/continuum/egress/EgressFetchHandler.java
- warp10/src/main/java/io/warp10/continuum/egress/EgressFindHandler.java
- warp10/src/main/java/io/warp10/continuum/egress/EgressSplitsHandler.java
- warp10/src/main/java/io/warp10/continuum/store/Constants.java
- warp10/src/main/java/io/warp10/script/functions/AUTHENTICATE.java
- warp10/src/main/java/io/warp10/script/functions/FETCH.java
- warp10/src/main/java/io/warp10/script/functions/FIND.java
- warp10/src/main/java/io/warp10/script/functions/FINDSTATS.java
- warp10/src/main/java/io/warp10/standalone/StandalonePlasmaHandler.java
- warp10/src/main/java/io/warp10/standalone/StandaloneSplitsHandler.java
This will allow read tokens that, among other things:
- can fetch data but cannot be used for authentication
- can be used for authentication but not to fetch data
- can used to find metadata but not actual data
This also offers an alternative solution for pure capabilities tokens as you can either:
- use a write token with .noauth, .nometa, .noupdate and .nodelete
- use a read token with .noauth, .nometa and .nofetch (instead of using a dummy app/owner/producer)
> Add .noauth, .nometa and .nofetch attributes for read tokens

- warp10/src/main/java/io/warp10/script/functions/TORLP.java
Previous import made the function fail when using pure WarpScript lib.
> Fix import of Bytes in ->RLP

- build.gradle
The REVISION file was generated too late for it to be included in the jar. This may generate WarpScript and Warp 10 jars without the REVISION file.
> Change REVISION generation task dependency

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
First bug fixed: when a subcycle series was empty, NaN values were pushed into the transient seasonal GTS, and then were propagated with the subsequent aggregations.
Second bug fixed: the aggregation did not take into account correctly missing values if input GTS was not filled.
> fix bugs that raised cryptic error messages in STL

- warp10/src/main/java/io/warp10/script/functions/MVEXTRACT.java
Currently an `Arrays.ArrayList` is pushed on the stack which is not consistent with all other functions.
> Make MVEXTRACT push ArrayList of lat/lon on the stack

- warp10/build.gradle
This PR removes `com.selesse.git.changelog` which is not maintained anymore and will not be compatible with Gradle 7.
Instead of listing all commits in the changelog, this new way of generating the changelog tries to list PRs:
- Commits applied directly to master are listed
- Only the merge of a PR is listed, all commits in the PR are not listed.
This method generates much more readable changelogs at the cost of:
- Being dependent to the way GitHub merges PRs (ie a commit message starting with "Merge pull request")
- Hiding merges of branches containing themselves merges of PRs. See for instance the merge of the 2.x branch.
Here is the changelog generated at this time. Links to issues and commits are added by GitHub, links to PRs are really in the changelog:
* Remove unused variables and …
> Update changelog generation to display PRs if possible

- warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java
When executing 
```
'WRITE'
'someclass{}'
0 MAXLONG
0
DELETE
```
the delete operation is aborted because there is more than 0 GTS to delete. This is the expected behavior.
However, because the HTTP connection is closed before all the content is read, a stack trace is logged because StandaloneDeleteHandler encounters a "Broken Pipe".
As the early abortion of a delete request is expected, the PR changes the code to simply log an info stating that the request was aborted instead of logging a stack trace.
> Catch and log early abortion of delete requests

- warp10/src/main/java/io/warp10/script/ext/debug/LOGMSG.java
- warp10/src/main/java/io/warp10/script/ext/debug/STDERR.java
- warp10/src/main/java/io/warp10/script/ext/debug/STDOUT.java
To flush stdout when using LOGMSG or STDOUT.
It might be better to add a function STDOUT.FLUSH, or to flush per default.
> force a flush of underlying PrintStream object in LOGMSG, STDOUT and STDERR

- warp10/build.gradle
Sometimes the `CHANGELOG.md` file was generated in the `warp10/` directory.
This PR makes sure the file is generated in the root directory of the project.
> Fix CHANGELOG.md output directory

- build.gradle
- warp10/build.gradle
This PR make sure Gradle tracks Thrift files and files generated by Thrift. Thus, they are not re-generated if either the thrift files or the generated files are left untouched.
The `clean` task now properly deletes classes generated by Thrift.
Also removed duplicate manifest configuration. Those keys were already set by `tasks.withType(Jar)` blocks.
> Better integrate thrift generation in gradle

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/functions/LFILTER.java
- warp10/src/main/java/io/warp10/script/functions/MFILTER.java
Introduces two new functions `LFILTER` and `MFILTER` with a lot of similarities with `LMAP` and `MMAP`. Instead of mapping the element, those functions filter the element according to a boolean-returning macro.
Like `LMAP` and `MMAP`, is is possible to push the index of the element or not. It is pushed by default.
While this logic is achievable through a macro, those functions execute in 2/3 of the time of the macro version.
> Add LFILTER and MFILTER

- warp10/src/main/java/io/warp10/script/functions/FETCH.java
- warp10/src/main/java/io/warp10/script/functions/FIND.java
When FIND or FETCH are called within a TIMEBOX call we may end up with long scans continuing some time after TIMEBOX interrupted the threads.
This PR adds a check for thread interrupted status in order to ensure early exit from the loops.
> Added checking of thread interruption to allow for early exit

- etc/conf.templates/distributed/20-warpscript.conf.template
- etc/conf.templates/standalone/20-warpscript.conf.template
In dist, soft and max were swapped and in standalone there were the same.
> Fix warpscript.maxbuckets in conf templates

- warp10/src/main/java/io/warp10/plugins/tcp/TCPManager.java
Currently, to limit the number of parallel connections the following is done:
- All incoming connections are accepted
- After accepting a connection, it is immediately closed if there are already `maxConnections` `TCPClients` running.
While this is not ideal, it appears that are no other option to implement this.
There currently an issue with accepted and open connections which are not handled by a running `TCPClient`, see #1022.
This is because the `ThreadPoolExecutor` is created with a pool of core=max=maxConnections threads and a  `LinkedBlockingQueue` of capacity `maxConnections`. So `maxConnections` `TCPClient`s could be accepted and running (thread pool capacity) and `maxConnections` `TCPClient`s could be accepted and waiting to be run (in the Queue).
The fix is to change the …
> Fix TCPClient stuck in LinkedBlockingQueue see #1022

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/functions/INDEXOF.java
Takes a List/Map/String/GTS/byte[] object, a value to look for and the maximum number of indexes.
Returns a list of indexes or keys.
Here is how it can be used:
```
[ 1 5 2 9 3 7 2 ] 2 0 INDEXOF
[ 2 6 ] == ASSERT
[ 1 5 2 9 3 7 2 ] 2 1 INDEXOF
[ 2 ] == ASSERT
{
'a' 1
'e' 5
'b' 2
'd' 9
'c' 3
'g' 7
'f' 2
}
2 0 INDEXOF
[ 'b' 'f' ] == ASSERT
{
'a' 1
'e' 5
'b' 2
'd' 9
'c' 3
'g' 7
'f' 2
}
2 1 INDEXOF
[ 'b' ] == ASSERT
'abojjabjpjifsdabojjfab'
'ab'
0
INDEXOF
[ 0 5 14 20 ] == ASSERT
'abojjabjpjifsdabojjfab'
'ab'
1
INDEXOF
[ 0 ] == ASSERT
'aaa'
'aa'
0
INDEXOF
[ 0 1 ] == ASSERT
NEWGTS
2 NaN NaN NaN 'a' ADDVALUE
5 NaN NaN NaN 'b' ADDVALUE
1 NaN NaN NaN 'a' ADDVALUE
'a' 0 INDEXOF
[ 0 2 ] == ASSERT
NEWGTS
2 NaN NaN NaN 'a' ADDVALUE
5 NaN NaN NaN 'b' ADDVALUE
1 NaN NaN NaN 'a' ADDVALUE
'a' 1 INDEXOF
[ 0 …
```
> Add INDEXOF to get the indexes of elements

- warp10/src/main/java/io/warp10/script/functions/EVAL.java
- warp10/src/main/java/io/warp10/script/functions/REPORT.java
- warpscript/build.gradle
The StoreClient interface has a method addPlasmaHandler which takes as parameter an interface which is not exported in the WarpScript jar. This prevents plugins from defining StoreClients. This PR exports this interface.
> Plasma.handler.interface

- warp10/src/main/java/io/warp10/continuum/store/Constants.java
- warp10/src/main/java/io/warp10/script/functions/EVAL.java
- warp10/src/main/java/io/warp10/script/functions/REPORT.java
//
// If the time units were not set in the config or the configuration not loaded
// we will attempt to use the System property. This is to allow some classes
// which depend on other constants in this class to still work even though no
// Warp 10 config was loaded. Before introducing this the lack of Warp 10 configuration
// would trigger a RuntimeException reporting missing time units and attempts to
// access any other constant from this class would throw a NoClassDefFoundException.
// Adding support for reading time units from system properties 
//
> System property support for setting time units.

- warp10/src/main/java/io/warp10/script/functions/GOLDWRAP.java
In some contexts wrappers are always stored in reverse chronological order, it is therefore useful to have an option to build "gold" wrappers with the choice of order.
The behavior of GOLDWRAP is unchanged, it is the equivalent of 'false GOLDWRAP'. Gold wrappers in reverse chronological order can be created using 'true GOLDWRAP'.
> Add order selection to GOLDWRAP

- etc/conf.templates/distributed/20-warpfleet.conf.template
- etc/conf.templates/standalone/20-warpfleet.conf.template
- warp10/src/main/java/io/warp10/script/WarpFleetMacroRepository.java
Some URLs may require parameters which would need to appear after the macro name. This PR adds the possibility to specify a macro placeholder '{macro}' in the repo URLs. If present, the macro path will be inserted where the placeholder is thus allowing for URLs of the type:
http://host/path/to/root/{macro}?param=foo
> Added support for macro placeholder in repo URLs

- warp10/build.gradle
Remove outputs.file definition to always run generateChanglog (no UP-TO-DATE state)
> Remove outputs.file for tasks generateChangelog

- warp10/src/main/java/io/warp10/script/functions/MAP.java
`[ $gts $mapper 0 0 0 ] MAP` is simplified into `[ $gts $mapper ] MAP`
> simplify single value MAP

- warp10/src/main/java/io/warp10/script/mapper/MapperAbs.java
- warp10/src/main/java/io/warp10/script/mapper/MapperCeil.java
- warp10/src/main/java/io/warp10/script/mapper/MapperDateTime.java
- warp10/src/main/java/io/warp10/script/mapper/MapperFinite.java
- warp10/src/main/java/io/warp10/script/mapper/MapperFloor.java
- warp10/src/main/java/io/warp10/script/mapper/MapperGeoClearPosition.java
- warp10/src/main/java/io/warp10/script/mapper/MapperGeoElevation.java
- warp10/src/main/java/io/warp10/script/mapper/MapperGeoLatitude.java
- warp10/src/main/java/io/warp10/script/mapper/MapperGeoLongitude.java
- warp10/src/main/java/io/warp10/script/mapper/MapperMaxX.java
- warp10/src/main/java/io/warp10/script/mapper/MapperMinX.java
- warp10/src/main/java/io/warp10/script/mapper/MapperMod.java
- warp10/src/main/java/io/warp10/script/mapper/MapperNPDF.java
- warp10/src/main/java/io/warp10/script/mapper/MapperParseDouble.java
- warp10/src/main/java/io/warp10/script/mapper/MapperRegExpReplace.java
- warp10/src/main/java/io/warp10/script/mapper/MapperRound.java
- warp10/src/main/java/io/warp10/script/mapper/MapperTick.java
- warp10/src/main/java/io/warp10/script/mapper/MapperToBoolean.java
- warp10/src/main/java/io/warp10/script/mapper/MapperToDouble.java
- warp10/src/main/java/io/warp10/script/mapper/MapperToLong.java
- warp10/src/main/java/io/warp10/script/mapper/MapperToString.java
Some mappers did support empty buckets, some failed with `can only be applied to a single value` error message. This was confusing, as the error message leads to DEDUP, not to UNBUCKETIZE.
> uniform support of empty buckets among available mappers

- warp10/src/main/java/io/warp10/script/functions/FETCH.java
Fix a bug when using labels presented by MACROMAPPER for example (unmodifiable map). There is no clean way to test if the input is an instance of unmodifiablemap, the only way is to catch the unsupported operation, or to clone the object.
> make sure FETCH will handle unmodifiable label map

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
- warp10/src/main/java/io/warp10/script/WarpScriptStack.java
- warp10/src/main/java/io/warp10/script/functions/SLEEP.java
When pushing data to external services (using HTTP or WEBCALL), we might need to respect a minimum period between requests. Current solution to do so is an infinite loop bounded by TIMEBOX, quite CPU intensive.
Adds `sleep.maxtime` capability.
> add SLEEP function and capability

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/script/functions/MAP.java
In case of a concurrent execution of MAP, sorting the outputTicks will lead to a concurrent modification exception.
So, I just check if the input is correctly sorted instead of always calling Collections.sort()
> check if MAP ticks input are sorted instead of sorting them

- warp10/src/main/java/io/warp10/script/functions/BUCKETIZECALENDAR.java
- warp10/src/main/java/io/warp10/script/functions/UNBUCKETIZECALENDAR.java
In BUCKETIZE.CALENDAR, the computation of the underlying bucketoffset wasn't correct in some cases.
In the preliminary calculations of bucketoffset and bucket index of lastbucket, we were sliding Epoch up to its congruent timestamp contained in the lastbucket using provided timezone parameter. Instead, we now use UTC timezone so this calculation does not depend on the timezone.
Also, for each addition or subtraction of multiple periods from an origin timestamp, we now always add all periods at once instead of adding a single period from a previous intermediate timestamp. With this change we avoid cases where less duration would have been added than expected if an intermediate timestamp would have landed in the margin of a period component (for example 28th of February instead of 29th).
> Fix BUCKETIZE.CALENDAR

- warp10/src/main/java/io/warp10/script/functions/SLEEP.java
fix #1183 
Here is a test that randomly fails (sleep lasts nearly 0 second) with parkNanos method :
```
// it should return lists of empty lists.
1 10
<%
DROP
[
1 20
<%
DROP 
<%
DROP
NOW 't1start' STORE
5 s SLEEP
//'sleep 5 done'
NOW $t1start -  'executionTime' STORE
$executionTime 5 s  200 ms ~= ! // execution time is not around 5s
<% $executionTime HUMANDURATION %> IFT
%> <% %> +
%> FOR
] 20 CEVAL
%> FOR
```
Here is a test to show that Thread interrupt is correctly managed by SLEEP:
```
// this should output "running" one or two times, 
// then the SLEEP interrupted exception
[
<% 
DROP
1 10 
<% 
'running' STDOUT 
<% 1 s SLEEP  %>
<% ERROR ->JSON STDOUT FAIL %>
<% %>
TRY
%> FOR 
%>
<% 
DROP
1 s SLEEP
'nope' MSGFAIL
%>
] 2 CEVAL
```
Both tests pass with Thread.sleep().
> change SLEEP implementation for concurrent execution

- warp10/src/main/java/io/warp10/script/functions/IDENT.java
`warp.ident` is defined into 00-warp.conf, but `IDENT` only look at System variables.
> fix IDENT function

- warp10/src/main/java/io/warp10/script/WarpScriptLib.java
This is a work in progress.
To do: remove duplicate reducers and fix naming incoherences.
To help define the correct changes to implement, in the following the reducers are grouped by their null handling behavior.
Remove null values:
- reducer.and.exclude-nulls
- reducer.min
- reducer.max
- reducer.mean.exclude-nulls
- reducer.median
- reducer.mad
- reducer.or.exclude-nulls
- reducer.sum
- reducer.join.forbid-nulls
- reducer.join.nonnull
- reducer.join.urlencoded
- reducer.var
- reducer.var.welford
- reducer.sd
- reducer.sd.welford
- reducer.count.exclude-nulls
- reducer.count.nonnull
- reducer.mean.circular.exclude-nulls
- reducer.rms.exclude-nulls
Keep null values:
- reducer.count
- reducer.count.include-nulls
Skip timestamp if there is at least one null value:
- reducer.and
- …
> Aggregator nameset cleaning

- warp10/src/main/java/io/warp10/continuum/ingress/IngressStreamUpdateHandler.java
- warp10/src/main/java/io/warp10/fdb/FDBUtils.java
- warp10/src/main/java/io/warp10/standalone/StandaloneIngressHandler.java
- warp10/src/main/java/io/warp10/standalone/StandaloneStreamUpdateHandler.java
When trying to ingest compact gts input format on a levelDB standalone, it fails with error 500 and no explaination.
The root cause is that FDBUtils static method `hasCriticalTransactionSize` is not available, because FDBUtils class static block will fail (FDB.selectAPIVersion(version) will fail).
I can fix FDBUtils, but I think is is better to skip the test when not using FDB as a store, for performances.
To test, try to ingest `https://warp10.io/assets/files/ibtracs-2010-2015.gts` on a leveldb 3.x standalone...
> fix leveldb multiline ingestion

- warp10/src/main/java/io/warp10/WarpConfig.java
Allow to generate easily a 999-migration3x.conf file that remove some configurations.
Example:
```
warpscript.extension.debug = 
warpscript.extension.hbase=     
warpscript.extension.inventory= 
```
Also allows space as a configuration value, when url encoded:
```
x = %20
```
Empty value are still not possible for configuration.
> allow to remove property

- warp10/src/main/java/io/warp10/continuum/egress/EgressFetchHandler.java
- warp10/src/main/java/io/warp10/continuum/egress/EgressFindHandler.java
- warp10/src/main/java/io/warp10/continuum/egress/EgressSplitsHandler.java
- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
- warp10/src/main/java/io/warp10/script/functions/FETCH.java
- warp10/src/main/java/io/warp10/script/functions/FIND.java
- warp10/src/main/java/io/warp10/standalone/StandaloneSplitsHandler.java
Ensure that GTS results from Directory requests are sorted when gskip/gcount are specified. This is of importance if there are several Directory instances.
> Added forced sorting of GTS when gskip/gcount is specified.

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
This impacted GOLDWRAP as GTS and the matching encoder could lead to different GOLDWRAPped versions.
> Fixed value optimization when sorting encoders

- warp10/src/main/java/io/warp10/script/functions/SHRINK.java
Fix `SHRINK` function.
Previously:
- when size was less than requested size, exception
- when size was equal, do nothing (no sort)
- when size was bigger than requested size, sort (or reverse sort), then shrink.
Now:
- when size greater than requested size : sort (or reverse sort) then shrink
- when size is less than requested size : let gts untouched
- can be applied on list of gts.
Documentation updated.
> update SHRINK behavior

- warp10/src/main/java/io/warp10/json/WarpScriptAuditStatementSerializer.java
- warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
- warp10/src/main/java/io/warp10/script/WarpScriptAuditStatement.java
- when not in multiline, `multiline.toString(); ` previously lead to a npe
- `/* "x": true, */ 42` was previously failing
- tab characters were previously tolerated at the beginning and end of each line (side effect of trim()). Now all control characters are valid separator
- statement number is replaced by position in line, easier for any debugging extension or code audit.
> Update of WarpScript parser

- crypto/src/main/java/io/warp10/crypto/SipHashInline.java
- warp10/src/main/java/io/warp10/continuum/Configuration.java
- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
- warp10/src/main/java/io/warp10/standalone/StandaloneDirectoryClient.java
Under JDK17, Incorrect array content was sometimes encountered, leading to incorrect labels id computation. This PR aims at adding robustness to the labels id computation and at improving its overall performance by reducing the amount of allocations.
> Fixes to labels id computation

- warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
When GTS is empty, MAP returns an empty GTS.
However, if the occurrence list is  set and not empty, the mapper should be applied on these ticks.
Currently, this is the case if there is at least one data point in the GTS but not when the GTS is empty.
This commit fixes it.
> fix empty GTS and not empty occurences list

- warp10/src/main/java/io/warp10/script/ext/logging/LOGEVENTTO.java
```
<'
not valid
'>
LOGEVENT->
```
leads to error (Cannot invoke "io.warp10.continuum.thrift.data.LoggingEvent.getAttributes()" because "event" is null)
> avoid npe exception on malformed LOGEVENTTO input

- warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java
- warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java
Delete fails with null pointer exception if `selector` query param is not set.
> fix(ingress): prevent null pointer on delete

- warp10/src/main/java/io/warp10/continuum/egress/EgressExecHandler.java
- warp10/src/main/java/io/warp10/continuum/sensision/SensisionConstants.java
- warp10/src/main/java/io/warp10/fdb/FDBPool.java
:wave: 
This PR implements a metric that allow to understand how saturated are the network threads of the FoundationDB client, only on egresses. 
It's very convenient to have in order to have tune the number of network threads needed, scanners...
> Add foundationdb client busyness metric on egress

- warp10/src/main/java/io/warp10/script/functions/MSTORE.java
Yes, it is a breaking change.
But this signature was never ever documented.
When combined with MCSTORE, this allows a easy way to store parameters, then default parameters :
```
<%
[ 'a' 'b' ] MSTORE
{
'a' 0
'b' 0
} MCSTORE
$a $b +
%> 'm' STORE
{ 'b' 4 } @m
```
> Selective MSTORE
