senx/warp10-platform

warp10/src/main/java/io/warp10/continuum/gts/ZIP.java
=> fix bug on ZIP function when handling a list with only singletons

warp10/src/test/java/io/warp10/script/ExportFunctions.java, warp10/src/test/java/io/warp10/test/tools/ExportFunctions.java
ExportFunctions extracts and categorize WarpScript functions from JavaLibrary and WarpScriptLib classes.
ExportFunctions produce a JSON on console output.
=> Export functions to JSON

build.gradle, settings.gradle
The hbase filter jar contains only 'org/apache/hadoop/hbase/filter/**'  classes from warp10 without any dependencies.
=> Adds Hbase filter task and publication

.travis.yml, build.gradle, warp10/src/main/java/io/warp10/Revision.java
First Travis step for Warp10
-> build without test and reports
=> Adds Travis IC for Warp10

warp10/src/main/java/io/warp10/continuum/Configuration.java, warp10/src/main/java/io/warp10/continuum/egress/HBaseStoreClient.java, warp10/src/main/java/io/warp10/continuum/store/Directory.java, warp10/src/main/java/io/warp10/continuum/store/Store.java
Add support for 'hbase.zookeeper.property.clientport' hbase option.
=> Add support for 'hbase.zookeeper.property.clientport' hbase option.

etc/conf-standalone.template, warp10/src/main/sh/package.sh, warp10/src/main/sh/warp10-standalone.bootstrap
- template moved into a dedicated directory
- hard path into standalone.path variable
- configuration tag for standalone version upgrade with docker
=> move configuration templates to a dedicated directory

warp10/src/main/java/io/warp10/continuum/WarpInit.java
=> remove hard coded key here

build.gradle, warp10/src/main/java/io/warp10/Revision.java
=> Adds bintray configuration for crypto & token's artefacts upload

warp10/src/main/java/io/warp10/continuum/KafkaOffsetCounters.java, warp10/src/main/java/io/warp10/continuum/sensision/SensisionConstants.java, warp10/src/main/java/io/warp10/continuum/store/Directory.java
This will prevent bad things from happening if Kafka ever decides to lose track of offsets...
=> Added ratchet mechanism to Kafka consumption in Directory

.travis.yml
=> retrieve thrift binaries from home.cityzendata.net

etc/conf-standalone.template, warp10/src/main/java/io/warp10/continuum/Configuration.java, warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneIngressHandler.java
Datalogging produces files with the UPDATE/META/DELETE operations.
Such files can later be replayed on a Warp 10 platform.
=> Datalogging for the standalone Warp 10

build.gradle, token/src/main/java/io/warp10/quasar/encoder/QuasarTokenDecoder.java, token/src/main/java/io/warp10/quasar/encoder/QuasarTokenEncoder.java, token/src/test/groovy/io/warp10/token/test/TestReadToken.groovy, token/src/test/groovy/io/warp10/token/test/TestRevokeToken.groovy, token/src/test/groovy/io/warp10/token/test/TestWriteToken.groovy, token/src/test/groovy/io/warp10/token/test/TokenTestCase.groovy
Token encoders upgrades in order to generate all token types for token lib.
Adds unit tests related to token lib
=> Updates token encoders

warp10/src/main/java/io/warp10/script/functions/STL.java
Default behaviour of STL is now non-robust to outliers. Default execution is faster.
=> Change defaults of STL function

etc/conf-standalone.template, warp10/src/main/sh/snapshot.sh, warp10/src/main/sh/warp10-standalone.init
add worf command
add LOG and *.log files in leveldb snapshots
increase default soft/hard limits
=> Standalone: add worf command - add LOG and *.log files in leveldb snapshots

warp10/src/main/java/io/warp10/script/functions/FROMTSELEMENTS.java
Fixed else if condition to expect a LIST
Changed exception message to include expected arg types
=> Bugfix: FROMTSELEMENTS expects a LIST not LONG

warp10/src/main/java/io/warp10/worf/Worf.java, warp10/src/main/java/io/warp10/worf/WorfCLI.java, warp10/src/main/sh/warp10-standalone.init, warp10/src/test/java/io/warp10/test/tools/ExportFunctions.java
The initial Token file will be not polluted by unnecessary lines (conf initialized...).
=> Adds quiet option to Worf

warp10/src/main/java/io/warp10/script/functions/REPLACE.java
REPLACE and REPLACEALL were called with wrong condition
=> Bugfix in REPLACE and REPLACEALL

etc/conf-inmemory.template
Reflect https://github.com/cityzendata/warp10-platform/blob/master/etc/conf-standalone.template#L355
=> Fix in.memory.depth template unit

etc/install/README.md, warp10/src/main/sh/warp10-standalone.init
=> Standalone init script: update worf command

warp10/src/main/java/io/warp10/script/functions/TOKENINFO.java
This patch adds tokens'extra labels in the output of TOKENINFO.
=> Undisclose embedded token labels in TOKENINFO

warp10/src/main/java/io/warp10/worf/WorfCLI.java, warp10/src/main/java/io/warp10/worf/WorfInteractive.java, warp10/src/main/sh/warp10-standalone.init
Enable fixed token for read token in interactive mode
Update Worf command line doc
Adds worfcli (interactive mode) in standanlone.init
=> Adds Worf in interactive mode from standanlone.init

warp10/src/main/sh/snapshot.sh, warp10/src/main/sh/warp10-standalone.sh
Allow the possibility to run several instances of Warp 10 on the same host with the use of one pid file
Restore the display of handy commands at the first start
=> Allow the possibility to run several instances of Warp 10 on the same host

warp10/src/main/java/io/warp10/script/binary/CondAND.java, warp10/src/main/java/io/warp10/script/binary/CondOR.java, warp10/src/main/java/io/warp10/script/binary/CondShortCircuit.java
Typical usage:
NULL 'a' STORE
<% [ <% $a ISNULL %> <% $a SIZE 0 == %> ] OR %>
<% 'Null or empty list' %>
IFT
=> Implementation of n-ary short circuit evaluation for OR and AND.

warp10/src/main/java/io/warp10/script/functions/HAVERSINE.java
Formula checked and tested using:
https://en.wikipedia.org/wiki/Haversine_formula
https://www.movable-type.co.uk/scripts/latlong.html
=> HAVERSINE: Fix formula by switching lat and lon.

warp10/src/main/java/io/warp10/script/functions/TYPEOF.java
(SET, BITSET, GEOSHAPE) added.
=> Added new types for TYPEOF

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/ext/inventory/FUNCTIONS.java, warp10/src/main/java/io/warp10/script/ext/inventory/InventoryWarpScriptExtension.java, warp10/src/main/java/io/warp10/script/ext/inventory/WARP10FUNCTIONS.java
New function in /WarpScriptLib.java : getListOfRegisteredFunctions
New files for inventory extensions.
=> Inventory extension

token/src/main/java/io/warp10/quasar/encoder/QuasarTokenEncoder.java
Add the missing `labels` param and fix typos
=> Fix documentation for qte.getReadToken

warp10/src/main/java/io/warp10/script/binary/EQ.java, warp10/src/main/java/io/warp10/script/functions/TYPEOF.java
-Added equality support of vectors and matrix, based on existing equal methods of RealMatrix and ArrayRealVector.
-Added types in TYPEOF : VECTOR MATRIX DATABAG
=> Matrix and Vector equality and typeof definition.

warp10/src/main/java/io/warp10/script/WarpScriptLib.java
Pfilter was already here and 100% OK... easy fix.
=> Pfilter now available

warp10/src/main/java/io/warp10/script/functions/BINTOHEX.java
The fuction was always operating on the same nipple.
=> Fix BINTOHEX function : stop iterating on the same nibble

warp10/src/main/java/io/warp10/script/functions/SNAPSHOT.java
Throw exception if the top of the stack is not a Long for countbased snapshots.
Throw exception if there is no mark in the stack for marked snapshots.
=> Fix snapshot

warp10/src/main/java/io/warp10/script/binary/EQ.java, warp10/src/main/java/io/warp10/script/binary/GE.java, warp10/src/main/java/io/warp10/script/binary/GT.java, warp10/src/main/java/io/warp10/script/binary/LE.java, warp10/src/main/java/io/warp10/script/binary/LT.java, warp10/src/main/java/io/warp10/script/binary/NE.java
Allows testing equality or difference on complex type (List, Map, ...)
Allows comparison involving NaN value
=> Comparison functions

warp10/src/main/java/io/warp10/script/processing/shape/PcurveTightness.java
Edwin Catmull and Raphael Rom are now happy.
=> Ptightness type correction

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/aggregator/RMS.java
Returns the RMS of buckets + last position
=> Reducer rms

warp10/src/main/java/io/warp10/script/WarpScriptLib.java
=> typo mappeN.rms.exclude-nulls

warp10/src/main/java/io/warp10/script/functions/MATH.java, warp10/src/main/java/io/warp10/script/functions/MATH2.java
Idea to make reflection calls faster.
=> Functions based on MATH2 can use (Long,Long) methods if available.

warp10/src/main/java/io/warp10/script/processing/image/Pblend.java, warp10/src/main/java/io/warp10/script/processing/image/Pcopy.java
=>  Pcopy without args now returns a PIMAGE 

warp10/src/main/java/io/warp10/script/processing/image/Pblend.java
Mode is now a string, as in Pfilter
=> Correction of Pblend signature

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/ext/debug/DebugWarpScriptExtension.java, warp10/src/main/java/io/warp10/script/ext/debug/TDESCRIBE.java, warp10/src/main/java/io/warp10/script/functions/TYPEOF.java
Usefull for beginner training or debugging.
Sample ouput :
"LIST [ LIST [ LONG ] ]",
"LIST [ empty MAP ]",
"LIST [ MAP { STRING : MAP { LONG : LIST [ GTS ] }  }  ]",
"LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ LIST [ ... (recursion limit reached) ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ] ]",
"LIST [ LIST [ GTS ] ]",
Limitations: it returns the type of the first element of list, or the first key/value
pair found.
=> TDESCRIBE function

warp10/src/main/sh/warp10-standalone.sh
Also correctly modify snapshot.sh with WARP10_HOME and LEVELDB_HOME.
=> Handle any character in WARP10_HOME.

warp10/src/main/java/io/warp10/continuum/egress/EgressExecHandler.java, warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java, warp10/src/main/java/io/warp10/script/WarpScriptExecutor.java, warp10/src/main/java/io/warp10/script/aggregator/Percentile.java, warp10/src/main/java/io/warp10/script/functions/BYTESTO.java, warp10/src/main/java/io/warp10/script/functions/DELETE.java, warp10/src/main/java/io/warp10/script/functions/DIGEST.java, warp10/src/main/java/io/warp10/script/functions/FETCH.java, warp10/src/main/java/io/warp10/script/functions/FIND.java, warp10/src/main/java/io/warp10/script/functions/FINDSTATS.java, warp10/src/main/java/io/warp10/script/functions/GZIP.java, warp10/src/main/java/io/warp10/script/functions/PARSESELECTOR.java, warp10/src/main/java/io/warp10/script/functions/PARTITION.java, warp10/src/main/java/io/warp10/script/functions/SECURE.java, warp10/src/main/java/io/warp10/script/functions/TOBYTES.java, warp10/src/main/java/io/warp10/script/functions/UNGZIP.java, warp10/src/main/java/io/warp10/script/functions/UNSECURE.java, warp10/src/main/java/io/warp10/script/functions/UNWRAP.java, warp10/src/main/java/io/warp10/script/functions/UNWRAPSIZE.java, warp10/src/main/java/io/warp10/script/functions/URLFETCH.java, warp10/src/main/java/io/warp10/script/functions/WEBCALL.java, warp10/src/main/java/io/warp10/script/functions/WRAP.java, warp10/src/main/java/io/warp10/script/functions/WRAPRAW.java, warp10/src/main/java/io/warp10/script/processing/rendering/PGraphics.java, warp10/src/main/java/io/warp10/udf/TUNWRAP.java
also add cause to the X-Warp10-Error-Message header.
=> Add/fix WarpScriptException causes if available

warp10/src/main/sh/snapshot.sh, warp10/src/main/sh/warp10-standalone.init, warp10/src/main/sh/warp10-standalone.sh
Export WARP10_USER
Fix call of snapshot when using base snapshot
=> Fix use of snapshot from warp10-standalone.sh

warp10/src/main/sh/snapshot.sh, warp10/src/main/sh/warp10-standalone.sh
Factorise user check and process check
=> Change process detection for docker compatibility

etc/conf-standalone.template
-removed duplicate line for warpscript.call.directory
-gather together CALL parameters
=> standalone configuration template slight change

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/functions/MINREV.java, warp10/src/main/java/io/warp10/script/functions/REVATLEAST.java
Usage:
'1.2.22' REVATLEAST
> true
'1.3' REVATLEAST
> false
=> Add the REVATLEAST function which can test revision numbers.

warp10/src/main/java/io/warp10/script/functions/ATINDEX.java, warp10/src/main/java/io/warp10/script/functions/ATTICK.java, warp10/src/main/java/io/warp10/script/functions/ELEVATIONS.java, warp10/src/main/java/io/warp10/script/functions/KURTOSIS.java, warp10/src/main/java/io/warp10/script/functions/LOCATIONS.java, warp10/src/main/java/io/warp10/script/functions/OPTDTW.java, warp10/src/main/java/io/warp10/script/functions/SIZE.java, warp10/src/main/java/io/warp10/script/functions/SKEWNESS.java, warp10/src/main/java/io/warp10/script/functions/TICKLIST.java, warp10/src/main/java/io/warp10/script/functions/VALUES.java
Warning: sorting removal can break code using ELEVATIONS and LOCATIONS sorting side-effect.
=> Use GTSStackFunction when relevant, remove unnecessary sorting, typos

warp10/src/main/java/io/warp10/script/binary/MOD.java
Warning, this will change the behavior of % as `12.2 2 %` will now work on doubles instead of truncating and working on longs.
=> MOD to work on decimal values.

warp10/src/main/java/io/warp10/script/functions/FORSTEP.java
It was fixed to 5000ms, whatever the MAXLOOP value.
=> Fix the time limit issue in FORSTEP

warp10/src/main/java/io/warp10/WarpConfig.java, warp10/src/main/java/io/warp10/continuum/Configuration.java, warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java, warp10/src/main/java/io/warp10/script/WarpFleetMacroRepository.java, warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/WarpScriptMacroLibrary.java, warp10/src/main/java/io/warp10/script/WarpScriptMacroRepository.java, warp10/src/main/java/io/warp10/script/WarpScriptStack.java, warp10/src/main/java/io/warp10/script/functions/MACROCONFIG.java
Allows macros to retrieve properties from the configuration file.
=> Macro config

warp10/src/main/java/io/warp10/script/functions/ADDDAYS.java, warp10/src/main/java/io/warp10/script/functions/ADDMONTHS.java, warp10/src/main/java/io/warp10/script/functions/ADDYEARS.java
Already taken care of just above in the code.
=> Remove unnecessary check.

warp10/src/main/java/io/warp10/script/binary/ADD.java
ArrayUtils already used elsewhere in the project. Not a new dependency.
=> Byte array concatenation

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/functions/TOBYTES.java, warp10/src/main/java/io/warp10/script/functions/TOLONGBYTES.java
new signature : `number numberOfBytes ->BYTES`.
if number is a double, numberOfBytes can be 4 or 8.
if number is a long, numberOfBytes can be 1 to 8.
=> Add ->LONGBYTES

warp10/src/main/java/io/warp10/script/functions/CROP.java, warp10/src/main/java/io/warp10/script/functions/FILLNEXT.java, warp10/src/main/java/io/warp10/script/functions/FILLPREVIOUS.java, warp10/src/main/java/io/warp10/script/functions/FILLVALUE.java
Changed the signature of FILL* functions.
Does not extends GTSStackFunction to avoid breaking the previous flatten behaviour on list of list of GTS.
=> FILLNEXT, FILLPREVIOUS, FILLVALUE can take a single GTS

warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java, warp10/src/main/java/io/warp10/continuum/ingress/IngressStreamUpdateHandler.java, warp10/src/main/java/io/warp10/continuum/store/Constants.java, warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneIngressHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneStreamUpdateHandler.java
Add support for restricting what write tokens can do
=> Write token attributes

warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java, warp10/src/main/java/io/warp10/script/functions/REDUCE.java
Allows this:
```
[ 
$lgts [] 
<%
DROP
1 NaN NaN NaN 1
%>
MACROREDUCER
T // Replace ticks
]
REDUCE
```
=> Add overrideTick option to REDUCE

warp10/src/main/java/io/warp10/script/formatted/FormattedWarpScriptFunction.java
do not allow unrecognized argument in argument map
=> Formatted patch

warp10/src/main/java/io/warp10/script/aggregator/HDist.java, warp10/src/main/java/io/warp10/script/aggregator/TrueCourse.java, warp10/src/main/java/io/warp10/script/aggregator/VDist.java
=> Removed unused tick ordering

warp10/src/main/java/io/warp10/script/functions/SUBLIST.java
Allows
```
[ 'a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' ]
-1 4 -2 SUBLIST
```
=> Range signature with step for SUBLIST

warp10/src/main/java/io/warp10/script/mapper/STRICTMAPPER.java
Allows this:
```
[ 
$lgts 
mapper.mean
-2 s 1 - DUP STRICTMAPPER 
0 -2 s 0 
] MAP
```
=> Make STRICTMAPPER work with timespans.

warp10/src/main/java/io/warp10/script/WarpScriptJarRepository.java
Fixes `newClassLoadersFingerprints.containsKey(hash)`
=> Fix key check for value check

etc/conf-standalone.template, warp10/src/main/java/io/warp10/continuum/Configuration.java, warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneIngressHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneStreamUpdateHandler.java
Ability to force a call to fsync when closing each datalog file
=> Added datalog.sync

etc/conf-distributed.template, etc/conf-standalone.template, warp10/src/main/java/io/warp10/script/ext/rexec/REXEC.java
added timeouts for REXEC and REXECZ requests.
=> added timeouts to REXEC

warp10/src/main/sh/warp10-standalone.sh
usefull with mqtt timeout.
is it OSX compatible ?
=> Wait for stop, allow clean restart with long plugin timeout + JMX

warp10/src/main/java/io/warp10/script/ElementOrListStackFunction.java, warp10/src/main/java/io/warp10/script/functions/ATINDEX.java, warp10/src/main/java/io/warp10/script/functions/DEDUP.java, warp10/src/main/java/io/warp10/script/functions/RELABEL.java, warp10/src/main/java/io/warp10/script/functions/TIMECLIP.java, warp10/src/main/java/io/warp10/script/functions/TIMESCALE.java, warp10/src/main/java/io/warp10/script/functions/TIMESHIFT.java, warp10/src/main/java/io/warp10/script/functions/TIMESPLIT.java
This class does not use a Map for parameters unlike GTSStackFunction so it is a tad faster.
This is also more flexible because it can be used on any type.
=> Abstract class to be inherited for WS function which can be applied on lists or element

warp10/src/main/java/io/warp10/script/functions/FETCH.java
To be consistent with FETCH without typeattr.
=> Remove producer and owner labels when FETCHing with typeattr

warp10/src/main/java/io/warp10/script/formatted/FormattedWarpScriptFunction.java, warp10/src/main/java/io/warp10/script/formatted/ListSpecification.java, warp10/src/main/java/io/warp10/script/formatted/MapSpecification.java, warp10/src/test/java/io/warp10/script/formatted/FormattedWarpScriptFunctionTest.java
Check sub types of Lists and Maps arguments of FormattedWarpscriptFunction instances.
Part 2/3 of PR #463 that is split.
Comments from PR #463 are answered.
=> Support for Lists and Maps in formatted functions

warp10/src/main/java/io/warp10/script/functions/QUANTIZE.java
also switch to ElementOrListStackFunction.
=> QUANTIZE now only accepts sorted and finite bounds

warp10/src/test/java/io/warp10/script/NestedListsShapeTest.java
Had forgot to change the unit test of HULLSHAPE after copy paste unit test of SHAPE
=> more complicated unit test for HULLSHAPE

warp10/src/main/java/io/warp10/script/functions/LMAP.java
=> preallocate result size list in LMAP

warp10/src/main/java/io/warp10/script/functions/TOLONGBYTES.java
A little improvement to build byte array faster from a list of long.
=> ToLongBytes can take a list of long

warp10/src/main/java/io/warp10/Py4JEntryPoint.java
error message when creating multiple entry points for a same gateway but with different conf
=> Informative error message

README.md, build.gradle, etc/conf-distributed.template, etc/conf-standalone.template, warp10/build.gradle, warp10/src/main/sh/package.sh, warp10/src/main/sh/warp10-standalone.sh
=> WarpStudio bundling

build.gradle
=> WarpStudio version bump

README.md, build.gradle, warp10/build.gradle, warp10/src/main/sh/package.sh, warp10/src/main/sh/warp10-standalone.sh
Removing WarpStudio from standard package
=> Removing WarpStudio from standard package

warp10/src/main/java/io/warp10/script/functions/IFT.java, warp10/src/main/java/io/warp10/script/functions/IFTE.java
Expect minimal performance improvement but improvement nonetheless.
=> Fix IFTE type check, IFT/IFTE explicit variable names and less type check

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/functions/STRINGFORMAT.java
Add different functionalities than TEMPLATE, specially the formatting of doubles.
=> Add STRINGFORMAT function to format strings using String.format

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/functions/HHCODETO.java, warp10/src/main/java/io/warp10/script/functions/TOHHCODE.java
Also fix condition and use Java 8 Long.parseUnsignedLong for speed-up.
=> Function to convert from/to hhcodes to handle NaN and NO_LOCATION.

warp10/src/main/java/io/warp10/script/processing/image/Pblend.java
=> fixed the Pblend function

warp10/src/main/java/io/warp10/plugins/http/HTTPWarp10Plugin.java
@hbs Sorry, I introduced a syntax problem.
=> Fix syntax: Add parameters about Listen Queue/Backlog in TCP

etc/conf.templates/distributed/00-warp.conf.template, etc/conf.templates/standalone/00-warp.conf.template
Some token feature were missing in standalone and distributed config template.
=> token features missing from config template

warp10/src/main/java/io/warp10/script/functions/ASREGS.java, warp10/src/main/java/io/warp10/script/functions/CSTORE.java, warp10/src/main/java/io/warp10/script/functions/POPR.java, warp10/src/main/java/io/warp10/script/functions/VARS.java
Added support for replacing variables in [ ... ] STORE construct. Fixed register allocation when registers are already used in the macro
=> Advanced register substitution

warp10/src/main/java/io/warp10/continuum/egress/EgressFetchHandler.java, warp10/src/main/java/io/warp10/continuum/store/Constants.java, warp10/src/main/java/io/warp10/script/functions/FETCH.java, warp10/src/main/java/io/warp10/script/functions/FIND.java
To account for new functionalities and standardization.
=> Rewrite FETCH and fetch endpoint parameters handling

etc/conf.templates/distributed/20-warpscript.conf.template, etc/conf.templates/standalone/20-warpscript.conf.template, warp10/src/main/java/io/warp10/continuum/Configuration.java, warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
allow in WarpScript :
```c
/**
* comment
*
*/
NOW
/************************************************************
*   comment
************************************************************/
NOW
/*---- Check gts status -----------------------------------------
*   All gts must now be checked
*-------------------------------------------------------------------*/
NOW
```
=> allow more comment style in WarpScript

warpscript/build.gradle
=> Update warpscript's build.gradle

warp10/src/main/java/io/warp10/script/formatted/RunAndGenerateDocumentationWithUnitTests.java
Searched if a formatted function has declared a certain method to use it when generating doc.
Now it also searches its parent's classes.
=> search also for method in parent class when generating doc

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/aggregator/Median.java, warp10/src/main/java/io/warp10/script/aggregator/Percentile.java
- median aggregator was not usable as reducer, or returned the wrong result.
- position median was done on raw hhcode
example of non working code : 
https://snapshot.senx.io/00059c2130c8d5f8-0-4-5f8666e22df55aa3
https://snapshot.senx.io/00059c21362565e0-0-7-025b60d11920474c
=> fix median and percentile aggregators bugs when used as reducer

warp10/src/main/java/io/warp10/script/functions/ADDDURATION.java, warp10/src/main/java/io/warp10/script/functions/DURATION.java
=> Addduration

etc/conf.templates/distributed/00-warp.conf.template, etc/conf.templates/standalone/00-warp.conf.template, warp10/src/main/java/io/warp10/continuum/Configuration.java, warp10/src/main/java/io/warp10/continuum/Encode.java, warp10/src/main/java/io/warp10/continuum/Pack.java, warp10/src/main/java/io/warp10/continuum/ThrottlingManager.java, warp10/src/main/java/io/warp10/continuum/egress/EgressFetchHandler.java, warp10/src/main/java/io/warp10/continuum/egress/EgressFindHandler.java, warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java, warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java, warp10/src/main/java/io/warp10/continuum/ingress/IngressStreamUpdateHandler.java, warp10/src/main/java/io/warp10/continuum/store/Constants.java, warp10/src/main/java/io/warp10/hadoop/Warp10RecordWriter.java, warp10/src/main/java/io/warp10/script/functions/FETCH.java, warp10/src/main/java/io/warp10/script/functions/FIND.java, warp10/src/main/java/io/warp10/script/functions/META.java, warp10/src/main/java/io/warp10/standalone/StandaloneDeleteHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneIngressHandler.java, warp10/src/main/java/io/warp10/standalone/StandalonePlasmaHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneStreamUpdateHandler.java
Add configuration to expose producer and owner labels for Geo Time Series retrieved from the Warp 10 Storage Engine.
=> Expose producer owner

warp10/build.gradle, warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/functions/TOGEOJSON.java
Creates a GeoJSON from a GEOSHAPE
=> Initial commit of ->GEOJSON

warp10/src/main/java/io/warp10/script/functions/TYPEOF.java
Also merged reducer, mapper and bucketizer under aggregator because they cannot be differentiated.
=> Add types and clean TYPEOF

warp10/src/main/java/io/warp10/continuum/gts/GTSOpsHelper.java, warp10/src/main/java/io/warp10/script/binary/ADD.java, warp10/src/main/java/io/warp10/script/binary/ComparisonOperation.java, warp10/src/main/java/io/warp10/script/binary/CondShortCircuit.java, warp10/src/main/java/io/warp10/script/binary/DIV.java, warp10/src/main/java/io/warp10/script/binary/MUL.java, warp10/src/main/java/io/warp10/script/binary/SUB.java
Addresses the comments in #701 because @pi-r-p is unavailable ATM. 
This PR passes this new test:
```
NEWGTS 'gtsDouble' RENAME 0 0 0 0 3.14 ADDVALUE 'gtsDouble' STORE
NEWGTS 'gtsLong' RENAME 0 0 0 0 42 ADDVALUE 'gtsLong' STORE
NEWGTS 'gtsLongNotAligned' RENAME 1 0 0 0 42 ADDVALUE 'gtsLongNotAligned' STORE
NEWGTS 'gtsBool' RENAME 0 0 0 0 T ADDVALUE 'gtsBool' STORE
NEWGTS 'gtsBoolNotAligned' RENAME 1 0 0 0 T ADDVALUE 'gtsBoolNotAligned' STORE
NEWGTS 'gtsEmpty' RENAME 'gtsEmpty' STORE
NEWGTS 'gtsEmptyBucketized' RENAME [ SWAP bucketizer.last 10 1 11 ] BUCKETIZE 0 GET 'gtsEmptyBucketized' STORE
NEWGTS 'gtsLongBucketized' RENAME 0 0 0 0 42 ADDVALUE [ SWAP bucketizer.last 10 1 11 ] BUCKETIZE 0 GET 'gtsLongBucketized' STORE
NEWGTS 'gtsBoolBucketized' RENAME 0 0 0 0 T ADDVALUE [ SWAP …
```
=> Fixes #698, supersedes #701, empty GTSs from operations are UNDEF and keep metas

warp10/src/main/java/io/warp10/script/binary/EQ.java, warp10/src/main/java/io/warp10/script/binary/NE.java
Allow equality test between rarer types such as FONT, MATCHER, KEY, CONTEXT, etc.
=> Use more precise type check for NE and EQ

warp10/src/main/java/io/warp10/WarpConfig.java, warp10/src/main/sh/warp10-standalone.sh
Extract all required configuration values in a single JVM run thus speeding up the launch process.
=> Config fetch

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/processing/image/Psize.java
Psize returns the size of a PGraphics or PImage instance.
=> Initial commit of Psize

warp10/src/main/java/io/warp10/script/functions/SUBLIST.java
This work exactly the same but clarify the code, in particular `la < -1 * size` and `lb < -1 * size` conditions which could never happen.
=> Make code clearer and cleaner for the range case of SUBLIST

warp10/src/main/java/io/warp10/script/functions/FETCH.java
=> Make sure a FETCH with MINLONG timespan does not overflow count

warp10/src/main/java/io/warp10/script/functions/BUCKETIZECALENDAR.java
=> fix bucketcount in BUCKETIZE.CALENDAR

warp10/src/main/java/io/warp10/script/functions/UNBUCKETIZECALENDAR.java
=> fix UNBUCKETIZE.CALENDAR for empty series

warp10/src/main/java/io/warp10/script/functions/ASREGS.java, warp10/src/main/java/io/warp10/script/functions/STORE.java
Replaces STORE on lists containing only register numbers by POPRs
=> Add optimization to ASREGS

warp10/src/main/java/io/warp10/script/binary/EQ.java, warp10/src/main/java/io/warp10/script/functions/GEOCOVER.java, warp10/src/main/java/io/warp10/script/functions/GEOHASHTO.java, warp10/src/main/java/io/warp10/script/functions/GEOUNPACK.java, warp10/src/main/java/io/warp10/script/functions/GeoIntersection.java, warp10/src/main/java/io/warp10/script/functions/GeoUnion.java, warp10/src/main/java/io/warp10/script/functions/TOGEOSHAPE.java
Also modify EQ so it can check GeoXPShapes equality.
=> Make sure all created GeoXPShapes contain sorted and deduped arrays

warp10/src/main/java/io/warp10/script/binary/NE.java
Same kind of fix than 09d5132ae2761371cbc71b24481901ac4cd32a54.
=> Fix possible NPE in NE.java

warp10/src/main/java/io/warp10/script/ext/sharding/DEVAL.java
Because URL hashcode does name resolution, see http://michaelscharf.blogspot.com/2006/11/javaneturlequals-and-hashcode-make.html
=> Switch from a HashMap using URLS to URIs 

warp10/src/main/java/io/warp10/continuum/gts/GTSOpsHelper.java, warp10/src/main/java/io/warp10/script/functions/NumericalBinaryFunction.java, warp10/src/main/java/io/warp10/script/functions/NumericalUnaryFunction.java
The work on the GTSs values the same way these functions work on Lists.
=> Make numerical functions work on GTSs

warp10/src/main/java/io/warp10/script/binary/ADD.java, warp10/src/main/java/io/warp10/script/binary/DIV.java, warp10/src/main/java/io/warp10/script/binary/MUL.java, warp10/src/main/java/io/warp10/script/binary/SUB.java
=> Simplify, factorize and uniformize the code of arithmetic operations

warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java, warp10/src/main/java/io/warp10/script/WarpScriptStack.java, warp10/src/main/java/io/warp10/script/functions/HIDE.java, warp10/src/main/java/io/warp10/script/functions/SHOW.java
=> Refactored HIDE/SHOW so 0 is interpreted as no levels instead of all levels

warp10/src/main/java/io/warp10/continuum/gts/INTERPOLATE.java, warp10/src/main/java/io/warp10/continuum/store/ParallelGTSDecoderIteratorWrapper.java, warp10/src/main/java/io/warp10/standalone/StandaloneMemoryStore.java
Convert operands to double or remove unnecessary Math.floor().
=> Fix integer divisions

warp10/src/main/java/io/warp10/continuum/DirectoryUtil.java, warp10/src/main/java/io/warp10/continuum/egress/HBaseStoreClient.java, warp10/src/main/java/io/warp10/continuum/store/Directory.java, warp10/src/main/java/io/warp10/standalone/StandaloneDirectoryClient.java, warp10/src/main/java/io/warp10/standalone/StandaloneParallelStoreClientWrapper.java, warp10/src/main/thrift/io_warp10_continuum_store_thrift_data.thrift
Internal modifications so classes are scanned in the order of their classId, thus returning results in lexicographic order of classId+labelsId.
=> Metadata ordering

warp10/src/main/java/io/warp10/continuum/egress/EgressFetchHandler.java, warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java, warp10/src/main/java/io/warp10/continuum/ingress/Ingress.java, warp10/src/main/java/io/warp10/continuum/ingress/IngressStreamUpdateHandler.java, warp10/src/main/java/io/warp10/script/functions/PARSE.java, warp10/src/main/java/io/warp10/standalone/StandaloneIngressHandler.java, warp10/src/main/java/io/warp10/standalone/StandaloneStreamUpdateHandler.java
More descriptive parse errors, including precise index of the error.
Updated http status codes:
500 error for general server-side error
400 for bad input/request
403 for bad token
429 for exceeded throttling limits
=> More detailed error messages for /update

warp10/src/main/sh/warp10-standalone.sh
=> Fix bootstrap issue when running warp10-standalone.sh

warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java, warp10/src/main/java/io/warp10/warp/sdk/MacroResolver.java
The MacroResolver class allows to register custom macro resolution mechanism. This will allow for example the definition of macros directly in FLoWS.
=> Initial commit of MacroResolver

warp10/src/main/java/io/warp10/script/processing/Pencode.java, warp10/src/main/java/io/warp10/script/processing/image/Presize.java
Add support for calling Pencode on an IMAGE instance.
=> Processing.pencode

warp10/src/main/java/io/warp10/script/filter/FilterBySize.java, warp10/src/main/java/io/warp10/script/formatted/ArgumentSpecification.java, warp10/src/main/java/io/warp10/script/formatted/DocumentationGenerator.java, warp10/src/main/java/io/warp10/script/formatted/FormattedWarpScriptFunction.java, warp10/src/main/java/io/warp10/script/formatted/ListSpecification.java, warp10/src/main/java/io/warp10/script/formatted/MapSpecification.java, warp10/src/main/java/io/warp10/script/formatted/RunAndGenerateDocumentationWithUnitTests.java, warp10/src/main/java/io/warp10/script/functions/shape/CHECKSHAPE.java, warp10/src/main/java/io/warp10/script/functions/shape/HULLSHAPE.java, warp10/src/main/java/io/warp10/script/functions/shape/PERMUTE.java, warp10/src/main/java/io/warp10/script/functions/shape/RESHAPE.java, warp10/src/main/java/io/warp10/script/functions/shape/SHAPE.java, warp10/src/test/java/io/warp10/script/formatted/FormattedWarpScriptFunctionTest.java
Deprecate FormattedWarpscriptFunction.
=> Deprecate formatted

warp10/src/main/java/io/warp10/script/ext/urlfetch/URLFETCH.java
This can happen as mentionned in https://github.com/senx/warp10-platform/pull/891#discussion_r599563267
=> URLFETCH: Fix NPE when response have no body

warp10/src/main/java/io/warp10/script/mapper/STRICTMAPPER.java
Make STRICTMAPPER accept macros as input to improve readability of some warpscripts
=> STRICTMAPPER on macros

README.md
Primarily to remove the old link to bintray download.
=> Update the README header

warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
=> fix a npe in WarpScript exception message

warp10/src/main/java/io/warp10/script/ext/sharding/DEVAL.java
Also small fixes and formatting.
=> Fix shardmodulus assignment

warp10/src/main/java/io/warp10/script/functions/MOTIONSPLIT.java
When used on a GTS with some points with location and some without, MOTIONSPLIT may miss a split.
For instance:
```
// @preview gts
NEWGTS
1 3 // 3 points WITH location
<% 'i' STORE $i m $i $i $i $i ADDVALUE %>
FOR
4 6 // 3 points WITHOUT location
<% 'i' STORE $i m NaN NaN NaN $i ADDVALUE %>
FOR
7 9 // 3 points WITH location
<% 'i' STORE $i m $i $i $i $i ADDVALUE %>
FOR
{ 'distance.split' 1 }
MOTIONSPLIT
```
In that case, the points with timestamp 3 and 7 are in the same split even though the distance between them is well above 1 meter, see the image below.
This PR fix that, see the image below
These changes pass the MOTIONSPLIT unit tests.
=> Fix MOTIONSPLIT to handle points with no location

warp10/src/main/java/io/warp10/ThrowableUtils.java, warp10/src/main/java/io/warp10/script/functions/FETCH.java
Also add missing space in error message.
=> Error message fallbacks to classname when exception have no message

warp10/src/main/java/io/warp10/continuum/Configuration.java, warp10/src/main/java/io/warp10/continuum/store/Constants.java, warp10/src/main/java/io/warp10/script/functions/DURATION.java, warp10/src/main/java/io/warp10/script/functions/FETCH.java, warp10/src/main/java/io/warp10/script/functions/FIND.java, warp10/src/main/java/io/warp10/script/functions/TIMEBOX.java
Add support for ISO 8601 periods in timeboxing capability
=> Timebox.period

warp10/src/main/java/io/warp10/script/ScriptRunner.java
Currently, runners scan all files like `${runner.root}/*/periodicity/*.mc2`
This PR makes runners also scan files like `${runner.root}/*/periodicity/**/*.mc2`
This allows more flexibility to organize files.
=> Make runners scan subdirectories

warp10/src/main/java/io/warp10/script/WarpScriptLib.java, warp10/src/main/java/io/warp10/script/mapper/MapperRegEx.java, warp10/src/main/java/io/warp10/script/mapper/MapperRegExpMatch.java, warp10/src/main/java/io/warp10/script/mapper/MapperRegExpReplace.java
```
NEWGTS
'The quick brown fox jumps over the lazy dog'
' ' SPLIT
<% 
NaN NaN NaN 5 ROLL ADDVALUE
%>
T FOREACH
[
SWAP
'(?!brown$).*o.*' mapper.regex.match
0 0 0 
]
MAP
JSONPRETTY
```
gives
```
[[ {
"c" : "",
"l" : { },
"a" : { },
"la" : 0,
"v" : [ [ 3, "fox" ], [ 5, "over" ], [ 8, "dog" ] ]
} ]]
```
=> Add mapper.regexp.match and mapper.regexp.replace

warp10/src/main/java/io/warp10/script/functions/REMOVE.java
also changed variable name to "removed" for more clarity
=> Convert remvoved byte to a Long

warp10/src/main/java/io/warp10/script/ext/rexec/REXEC.java
Very hard to reproduce. 
Sometimes, SNAPSHOT and OPB64 conversion are not done server side...
=> rexec may not flush

BUILDING.md
Tested on a ubuntu 21.10 fresh install.
=> Add detailed build instructions for thrift and jar update

warp10/src/main/java/io/warp10/script/functions/BUCKETIZECALENDAR.java
aggregate when using a macro as a bucketizer
=> bugfix BUCKETIZE.CALENDAR

warp10/src/main/java/io/warp10/hadoop/WarpScriptInputFormat.java, warp10/src/main/java/io/warp10/hadoop/WarpScriptRecordReader.java
This PR introduces the possibility to specify WarpScript code returning a macro. Until now the only way this could be done was to specify a file using the percent + path syntax, which proved cumbersome in some cases as an external file had to be attached.
=> Wsif.macro

warp10/src/main/java/io/warp10/continuum/egress/EgressFetchHandler.java
Disabled the use of the GTS file cache in cases when there is no network connection which could timeout while data is fetched.
=> Egress.fetch.cache

warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Optimize subserie extraction when overwriting is not requested by relying on System.arraycopy to extract the GTS slice.
=> Subserie.opt

warp10/src/main/java/io/warp10/script/functions/ECRECOVER.java
When using recovering public keys from ECDSA signatures, several candidates exist. Systems such as Bitcoin and Ethereum  embed a recovery id which identifies the actual key among candidates.
This recovery id is linked to the x and y coordinates of the R point computed during the verifying process, therefore using the recovery id is only possible if the coordinates are exposed. This is what this PR adds.
The PR also fixes an off by one error when iterating over cofactors to identify candidate keys.
=> Fixed issue with cofactor iteration. Added option to output R coordinates for use of recovery ids

warp10/src/main/java/io/warp10/script/binary/DIV.java, warp10/src/main/java/io/warp10/script/binary/MUL.java, warp10/src/main/java/io/warp10/script/binary/SUB.java
Fixes #1124 
Operation | this PR | current master
-- | -- | --
<% MAXLONG 2 / %> | 4611686018427387903 | 4611686018427387903
<% NEWGTS [ 0 MAXLONG ] ADDVALUE NEWGTS [ 0 2 ] ADDVALUE / VALUES 0 GET %> | 4611686018427387903 | 4611686018427387904
<% MAXLONG 0 / %> | / by zero | / by zero
<% NEWGTS [ 0 MAXLONG ] ADDVALUE NEWGTS [ 0 0 ] ADDVALUE / VALUES 0 GET %> | / by zero | 9223372036854775807
<% MAXLONG 1 - 2 + %> | -9223372036854775808 | -9223372036854775808
<% NEWGTS [ 0 MAXLONG 1 - ] ADDVALUE NEWGTS [ 0 2 ] ADDVALUE + VALUES 0 GET %> | -9223372036854775808 | -9223372036854775808
<% MAXLONG 1 - 2 - %> | 9223372036854775804 | 9223372036854775804
<% NEWGTS [ 0 MAXLONG 1 - ] ADDVALUE NEWGTS [ 0 2 ] ADDVALUE - VALUES 0 GET %> | 9223372036854775804 | 9223372036854775807
<% MAXLONG 2 / 1 + 2 * …
=> fix binary ops for two LONG gts

warp10/src/main/java/io/warp10/script/WarpScriptLib.java
Linked to #1120 import refactor.
=> fix building problem linked to wildcard import refactor

warp10/src/main/java/io/warp10/script/ext/http/HTTP.java
```
{
'url' 'http://localhost:8088/api/v0/exec'
'timeout' 10 s
}
HTTP
```
=> add HTTP timeout

warp10/src/main/java/io/warp10/script/functions/BUCKETIZECALENDAR.java, warp10/src/main/java/io/warp10/script/functions/UNBUCKETIZECALENDAR.java
Reverts senx/warp10-platform#1185
=> Revert "Fix BUCKETIZE.CALENDAR"

warp10/src/main/java/io/warp10/script/ext/http/HTTP.java
Consistent with REXEC capability.
=> http capability may contain a url filter

etc/conf.templates/distributed/00-secrets.conf.template, etc/conf.templates/distributed/99-quickstart.conf.template, etc/conf.templates/standalone/00-secrets.conf.template, etc/conf.templates/standalone/10-runner.conf.template
This is a preliminary work to the refactoring of bootstrap in warp10.sh
=> Cleaned up key definitions

warp10/src/main/java/io/warp10/script/functions/TIMEBOX.java
=> fix TIMEBOX STOP handling

warp10/src/main/java/io/warp10/script/MemoryWarpScriptStack.java
Solve recursion problem with CEVAL
=> atomic counter for recursion

warp10/src/main/java/io/warp10/leveldb/WarpInit.java, warp10/src/main/sh/warp10.sh
Adds a command to quickly recreate leveldb after rm -rf /opt/warp10/leveldb/*
=> add leveldbinit command to bash

warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Fix last bucket timestamp index, in case of duplicate timestamps.
=> fix issue #1276

warp10/src/main/java/io/warp10/fdb/FDBUtils.java
=> Fixed retrieval of tenant info which could fail with error 1039 when using mutiple FDB clients

warp10/src/main/java/io/warp10/script/functions/JSONTO.java
Make result consistent with all the MAP functions in WarpScript.
(MSORT won't fail for example)
=> TOJSON now outputs a linkedhashmap

warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java
Prior repeated calls to remove impacted performance a lot when sorting with large list of ranges
=> Optimized sorting by keeping the range list untouched unless it grew too much

warp10/src/main/java/io/warp10/script/binary/ADD.java, warp10/src/main/java/io/warp10/script/binary/DIV.java, warp10/src/main/java/io/warp10/script/binary/MUL.java, warp10/src/main/java/io/warp10/script/binary/SUB.java
Refactor creation of GTS binary ops
=> Optimize GTS binary functions

Jenkinsfile, warp10/build.gradle, warp10/src/main/sh/package.sh
Add Warp 10 archive signature and checksum
Ask to publish only if head is a tag
=> Release artifacts

warp10/src/main/java/io/warp10/script/WarpScriptMacroLibrary.java
Macros can be expired using MACROTTL
=> Added use of cache for macros in the classpath. 

warp10/src/main/java/io/warp10/leveldb/SSTINFO.java, warp10/src/main/java/io/warp10/leveldb/WarpReport.java, warp10/src/main/java/io/warp10/script/ext/stackps/WSINFO.java, warp10/src/main/java/io/warp10/script/ext/token/TOKENDUMP.java, warp10/src/main/java/io/warp10/script/ext/token/TOKENGEN.java, warp10/src/main/java/io/warp10/script/functions/ATTRIBUTES.java, warp10/src/main/java/io/warp10/script/functions/CHRONOSTATS.java, warp10/src/main/java/io/warp10/script/functions/ERROR.java, warp10/src/main/java/io/warp10/script/functions/LABELS.java, warp10/src/main/java/io/warp10/script/functions/RSAGEN.java, warp10/src/main/java/io/warp10/script/functions/TOENCODERS.java, warp10/src/main/java/io/warp10/script/functions/TOGTS.java, warp10/src/main/java/io/warp10/script/functions/TOKENINFO.java
Avoid error when using MSORT:
MSORT operates on a map created by {} or ->MAP.
=> Use LinkedHashMap when applicable

warp10/src/main/sh/warp10.sh
`999-custom.conf` will be read after `99-init.conf`
=> Fix sorting of config files

warp10/src/main/java/io/warp10/script/functions/SHRINK.java
=> fix SHRINK with MINLONG MAXLONG value

warp10/src/main/java/io/warp10/continuum/gts/GTSHelper.java, warp10/src/main/java/io/warp10/script/functions/UNBUCKETIZECALENDAR.java
=> Fix last bucket and last tick mismatch in calendar unbucketization

warp10/src/main/java/io/warp10/script/WarpScriptStack.java, warp10/src/main/java/io/warp10/script/functions/TOKENINFO.java
Add a new capability to expose token attributes in TOKENINFO.
=> Add tokenattr cap to expose token attributes
